### ISSUE TITLE
Parsing "mo" time duration is not supported

### ISSUE THREAD

**Issue by lubotorok** [gmessner/gitlab4j-api#104]
When entering issue time longer than 20x8 hours, GitLab is presenting it as 1mo (1 month). I am getting errors when API is parsing those values. It seems that API's DurationUtils class does not support this value. Tests are not written for this value as well. Please, correct this. Thank you.

**Comment by gmessner** [comment]
@lubotorok 
Not a simple fix, because the logic looks for 1 character units.  I will fix sometime this week and let you know when it has been fixed.

**Comment by gmessner** [comment]
@lubotorok 
Support for month ("mo") durations has been added and tested.  Is available in release 4.7.3.
