### ISSUE TITLE
Reimplement login/password authentication via OAuth2

### ISSUE THREAD

**Issue by slonopotamus** [gmessner/gitlab4j-api#111]
Even with gitlab-10.2 it is still possible to authenticate using login/password pair via OAuth2: https://docs.gitlab.com/ce/api/oauth2.html#resource-owner-password-credentials

For example, that's how we did it in git-as-svn: https://github.com/slonopotamus/git-as-svn/commit/b434b39deb951b4614bb6459ae04f0a6014b08b6#diff-3af4173981772a146cfacf15b38b9531

**Comment by gmessner** [comment]
OAuth2 login support has been added to release 4.7.7. GitLabApi.oauth2Login() methods have been added, and GitLabApi.login() methods automatically try the OAuth2 login if the session login false with a 404 error.
