### ISSUE TITLE
Successful GroupApi.removeMember throws GitLabApiException

### ISSUE THREAD

**Issue by neuronfarms** [gmessner/gitlab4j-api#113]
// even when successful, the following GroupApi call throws a GitLabApiException
try {
groupApi.removeMember(foundGroup.getId(), gitlabUser.getId());
} catch(GitLabApiException e) {
System.out.println(e.getHttpStatus()); // prints 200
System.out.println(e.getMessage());   // prints OK
System.out.println(e.getReason());     // prints OK
}

**Comment by gmessner** [comment]
V3 of the GitLab API returns OK, V4 of the GitLab API returns NO_CONTENT.

It appears that you are going against a V3 GitLab API using a V4 connection (the default for GitLab4J).  To set up your connection for a V3 GitLab server, add the version parameter when creating the GitLabApi instance, for example:

```// Create a GitLabApi instance to communicate with your GitLab server using GitLab API V3
GitLabApi gitLabApi = new GitLabApi(ApiVersion.V3, 
    "http://your.gitlab.server.com", "YOUR_PRIVATE_TOKEN");
```
I have added a unit test to verify this.
