### ISSUE TITLE
I cannot get the javax.ws.rs to download using ivy or sbt (solved)

### ISSUE THREAD

**Issue by sductor** [gmessner/gitlab4j-api#115]
When I try to use gitlab4j-api library using ivy or sbt, I get the following error
::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: javax.ws.rs#javax.ws.rs-api;2.1!javax.ws.rs-api.${packaging.type}
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

In fact gitlab4j-api is not responsible at all.
The bug come from this use of ${packaging.type} which appears to be only usable with plain maven, which apparently won't even try to resolve the value and directly put a jar.

As I wasted 2 days attempting to understand what this was about, having few knowledge for this kind of things, here are the two threads that resolve it.

https://github.com/jax-rs/api/issues/571
https://github.com/jax-rs/api/issues/572

Maybe the admin will want to keep this issue hanging around for those who encounter the same problem.

Greetings

**Comment by gmessner** [comment]
@sductor 
I'll get something added to the README.md for Ivy and SBT users, pointing to the two issues at jax-rs.  Once added I'll close this issue.

**Comment by sductor** [comment]
Gradle seems concerned also.
The comment of 10 oct from sslavic worked well from me on sbt. Just adding:

libraryDependencies += "javax.ws.rs" % "javax.ws.rs-api" % "2.1" artifacts( Artifact("javax.ws.rs-api", "jar", "jar")), // this is a workaround for https://github.com/jax-rs/api/issues/571

Thanks for the work

**Comment by gmessner** [comment]
Added comment to README.md referencing the JAX-RS issues.

**Comment by VenkataMR** [comment]
Hi, Both the links are not enabled. Can you pls help with the resolution of "packaging.type" issue.
