### ISSUE TITLE
sudo functionality is inconvenient

### ISSUE THREAD

**Issue by slonopotamus** [gmessner/gitlab4j-api#118]
Currently, `GitLabApi` mutates itself when caller wants to use sudo functionality, but.

1. This cannot be safely used in multithreaded environment
2. `GitLabApi` doesn't provide any means to clone its instance (so cloned one would be mutated for sudo and original one kept untouched)

Ideally, sudo should be configurable per-request, giving the same flexibility that is available if user doesn't use gitlab4j-api at all and directly issues HTTP requests to GitLab, *without* modifying `GitLabApi` instance.

**Comment by gmessner** [comment]
I have added the ability to fetch the authToken and tokenType (#119) (and other properties) so you can now create a copy of an GitLabApi instance. I've also created duplicate() method that will duplicate an instance of GitLabApi. I would recommend using this duplicate() method to create a copy of a GitLabApi instance.

It would be difficult to add per request capability for sudo, however, it can be turned on and off before and after an API call:
```
gitLabApi.sudo(TEST_SUDO_AS_USERNAME);
User user = gitLabApi.getUserApi().getCurrentUser();
gitLabApi.unsudo();
```
I would recommend using ThreadLocal and create a GitLabApi instance for each thread if you must have multiple threads going against the API at the same time.

Another option would be to create a new instance of GitLabApi for each invocation.  I've modified the GitLabApi class to use lazy instantiation of the sub APIs to make it a bit more lightweight.

These mods are available in release 4.7.9.
