### ISSUE TITLE
gitlab4j-api isn't thread-safe?

### ISSUE THREAD

**Issue by slonopotamus** [gmessner/gitlab4j-api#120]
`org.gitlab4j.api.utils.ISO8601` stores `SimpleDateFormat` in static fields and it seems like they can be accessed from multiple threads when deserializing responses from concurrent GitLabApi calls (for example, via `org.gitlab4j.api.utils.JacksonJson.JsonDateDeserializer#deserialize`.

However, `SimpleDateFormat` isn't thread-safe.

**Comment by gmessner** [comment]
I've made everything in org.gitlab4j.api.utils.ISO8601 thread safe using ThreadLocal storage.  Is available in release 4.7.9
