### ISSUE TITLE
printing_merge_request_link_enabled flag for ProjectApi

### ISSUE THREAD

**Issue by ryanm35** [gmessner/gitlab4j-api#124]
Would it be possible to add support for the printing_merge_request_link_enabled flag when creating a project? (https://docs.gitlab.com/ce/api/projects.html#create-project-for-user)

Thanks

**Comment by gmessner** [comment]
The ability to set printing_merge_request_link_enabled when both creating and updating a project has been added and is available in release 4.7.11.
