### ISSUE TITLE
Replacement for login method

### ISSUE THREAD

**Issue by augi** [gmessner/gitlab4j-api#128]
The `GitLabApi.login` method is deprecated because this functionality was removed in GitLab 10.2.

Are you looking for a replacement of this method? So to be able to get instance of `GitLabApi` just from `url`, `username` and `password`.

My use-case is simple - I'm executing `gitlab/gitlab-ce` Docker image as part of my integration tests and I need access it. So I've set the `GITLAB_ROOT_PASSWORD` as described [here](https://docs.gitlab.com/ce/administration/environment_variables.html). Unfortunately, I'm not able to set the access token so easily :(

**Comment by gmessner** [comment]
This functionality was implemented in GitLab4J in release 4.7.7.  Does it not work for you?

Look at all the oauth2Login() methods in the GitLabApi class.  Here are the javadocs to one of the methods, the method is overloaded with 4 different ways to call it:

http://www.messners.com/gitlab4j-api/javadocs/org/gitlab4j/api/GitLabApi.html#oauth2Login-java.lang.String-java.lang.String-java.lang.String-

**Comment by augi** [comment]
Ah, sorry, I missed that it was already resolved in #111.

I was confused because I tried to use `GitLabApi.create` method that is deprecated. As it now just calls `GitLabApi.login` method (that is not deprecated because there is fallback to OAuth2 login) maybe you could remove deprecation also from the `create` method. What do you think?

**Comment by gmessner** [comment]
@augi 
I have clarified the Javadoc messaging around this, if this clarification works for you, please close this issue, otherwise, I will be looking for suggestions.

As far as the fall-forward to OAuth2, once 10.2+ becomes more prominent, the plan is to make the OAuth2 the primary method, and will fallback to Session login on failure.

**Comment by augi** [comment]
It's perfect now, thanks!
