### ISSUE TITLE
Outdated Webhook does not support "Job Hook" rename

### ISSUE THREAD

**Issue by armsnyder** [gmessner/gitlab4j-api#130]
"Build Hook" was renamed to "Job Hook" in GitLab v9.3.0.

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/11287

This project's WebHookManager is still using the old "Build Hook" when validating the incoming request, so you get a ```GitLabException "Unsupported X-Gitlab-Event, event Name=Job Hook"``` for all job events.

**Comment by maguro** [comment]
The JSON for Job events seems to be different than Build events.  Does support for 

    object_kind: "job" 

need to be added?

**Comment by gmessner** [comment]
@maguro 
I have opened a new issue to audit all of the webhook events to make sure they are up to date with the GitLab documentation.  The Job Event will be one of the updates.  See **Audit and update webhook events - #357** for more information.

**Comment by gmessner** [comment]
@maguro 
#357 has been completed and release 4.11.0 is available with the fixes.

**Comment by maguro** [comment]
Holy Toledo.  You’re awesome!
