### ISSUE TITLE
ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl

### ISSUE THREAD

**Issue by mcolburn** [gmessner/gitlab4j-api#133]
I use maven.

I have tried gitlab4j-api 4.7.16 and 4.7.17, with the same problem occurring.

When I try to use `gitLabApi.getProjectApi().getProjects()` or `gitLabApi.sudu("someuser"`

I get

`org.gitlab4j.api.GitLabApiException: java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl`

I have even tried adding the gitlab4j build dependencies to my pom, but I get the same ClassNotFoundException for com.sun.ws.rs.ext.RuntimeDelegateImpl.

**Comment by gmessner** [comment]
@mcolburn 
Can you try  gitlab4j-api 4.7.15 and let me know the results?

4.7.16 and 4.7.17 made some changes to support Java 9 and it looks like those are causing issues.  If they are we will be backing them out.

**Comment by mcolburn** [comment]
Same error running 4.7.15.

**Comment by gmessner** [comment]
@mcolburn 
When you tried 4.7.15 did you remove the dependencies from your POM?  Also, what version of Java are you using?

**Comment by mcolburn** [comment]
Yes, I tried it both ways.  With and without the dependencies.  I am using Java 8.

**Comment by gmessner** [comment]
You must have something in your dependencies that is fulfilling the javax.ws.rs dependency, but not fully, Would it be possible for you to share your pom so I can take a look?

When you tried 4.7.15, did you do a clean before building?  Not sure it will help, but just a thought.  Also, I know you indicated that you tried with and without the dependencies, I guarantee if you had the dependencies in your POM with 4.7.15 it will cause a problem.

**Comment by mcolburn** [comment]
Yes. I did do a clean of the project.  Here is the POM.  I added .txt to the extension so it would upload.

[pom.xml.txt](https://github.com/gmessner/gitlab4j-api/files/1647370/pom.xml.txt)

**Comment by mcolburn** [comment]
I just now create a new Maven project with only gitlab4j-api as the dependency.  It works with 4.7.15.  And, with 4.7.17.  So, as you said, there must be some dependency conflict, and therefore the problem is on my end.  I will close it once I hear back from you.
