### ISSUE TITLE
Email field for member doesn't exist

### ISSUE THREAD

**Issue by Spenhouet** [gmessner/gitlab4j-api#134]
I did see that the `Member` class has the field `Email` but based on the current documentation the email address of a member isn't returned:  https://docs.gitlab.com/ee/api/members.html

Therefore `member.getEmail()` always returns null (as far as I can see).

I guess the email was removed from the GitLab API sometime (I couldn't find anything on the GitLab issue page).

**Comment by gmessner** [comment]
@Spenhouet 
The email being part of member pre-dates V3, it will be removed in the next release.

**Comment by gmessner** [comment]
This has been fixed in release 4.8.0
