### ISSUE TITLE
Cloning a project?

### ISSUE THREAD

**Issue by mbush78** [gmessner/gitlab4j-api#142]
I'm not seeing an actual way to clone a given project after its been found. Is that in here and I just over looked it or do I need to use another api, like JGit, to the act on the info I pulled from this one ?

**Comment by gmessner** [comment]
Unfortunately, the GitLab API (which this project wraps) doesn't support clone.  Clone requires things to happen on the client side.  You would either need to use JGit or you invoke git as a process.

**Comment by mbush78** [comment]
thanks, wanted to be sure I wasn't overlooking it.
