### ISSUE TITLE
Notification settings API?

### ISSUE THREAD

**Issue by dbdahl** [gmessner/gitlab4j-api#143]
Does gitlab4j-api support the notification settings API?

https://docs.gitlab.com/ce/api/notification_settings.html

I am trying to disable email notifications for some groups and projects.

Thanks for your software!

**Comment by gmessner** [comment]
Currently does not have this functionality.  Will add this API and release with the next release (in the next week or so).

**Comment by gmessner** [comment]
@dbdahl 
The NotificationSettingsApi has been added and released in version 4.8.4.

**Comment by dbdahl** [comment]
@gmessner 
Wow, thanks for being so responsive!
