### ISSUE TITLE
Unrecognized SSL message, plaintext connection?

### ISSUE THREAD

**Issue by ricky001** [gmessner/gitlab4j-api#145]
The jar is working file for 2 hours i am getting the info  from Gitlab, but suddenly it will throw error
Unrecognized SSL message, plaintext connection?
I am using HTTPS for connection, please provide your inputs how to resolev this error.

**Comment by gmessner** [comment]
@ricky001 
I would need a lot more information, a stack trace would be especially helpful.  

My initial inclination would be that this is somewhere outside the of gitlab4j, but without additional information it is very difficult to come to any conclusions.

**Comment by gmessner** [comment]
@ricky001 
Can this be closed?

**Comment by ricky001** [comment]
Hello @gmessner  yes we can close it
