### ISSUE TITLE
Support for new arguments in createMergeRequest method

### ISSUE THREAD

**Issue by augi** [gmessner/gitlab4j-api#146]
The `createMergeRequest` method could now support following arguments: `target_project_id`, `labels`, `milestone_id`, `remove_source_branch`. See [the API description](https://docs.gitlab.com/ce/api/merge_requests.html#create-mr).

If you want then I can prepare a PR.

Btw. thanks for this great library!

**Comment by gmessner** [comment]
@augi 
That would be great if you could submit a PR.  I do have one request, could you create this as a new method?  I try to avoid breaking anyone's existing code.
