### ISSUE TITLE
failed to map MergeRequest note event string to Object

### ISSUE THREAD

**Issue by lethe3000** [gmessner/gitlab4j-api#149]
gitlab version: 10.5.1

`
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
return objectMapper.readValue(content, Event.class);
`

And error as below:

com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `org.gitlab4j.api.webhook.NoteEvent$NoteableType` from String "MergeRequest": value not one of declared Enum instance names: [MERGE_REQUEST, ISSUE, SNIPPET, COMMIT]

**Comment by gmessner** [comment]
@lethe3000 
Good find, there is a small bug in the NoteableType causing this, will fix later today and release with a few other updates.

**Comment by gmessner** [comment]
This should be fixed in the just-released GitLab4J-API Release 4.8.5, if you can verify and close this issue I would appreciate it.

**Comment by lethe3000** [comment]
Looks good for me.
thank you very much to respond fast to fix this issue
