### ISSUE TITLE
null is returning for get_addition() and get_deletion() for a commit info

### ISSUE THREAD

**Issue by ricky001** [gmessner/gitlab4j-api#150]
null is returning for get_addition() and get_deletion() for a commit info

**Comment by gmessner** [comment]
There are no methods called get_addition() and get_deletion() in the API.

I assume that you are looking at the Commit object getCommitStats().getAdditions() and getDeletions().  If so these will only be populated when fetching a single commit using the CommitsApi:
```
    /**
     * Get a specific commit identified by the commit hash or name of a branch or tag.
     *
     * GET /projects/:id/repository/commits/:sha
     *
     * @param projectId the project ID that the commit belongs to
     * @param sha a commit hash or name of a branch or tag
     * @return the Commit instance for the specified project ID/sha pair
     * @throws GitLabApiException GitLabApiException if any exception occurs during execution
     */
    public Commit getCommit(int projectId, String sha) throws GitLabApiException {
        return (getCommit(projectId, sha, null));
    }
```

See the GitLab API docs for more info: https://docs.gitlab.com/ee/api/commits.html#get-a-single-commit

**Comment by gmessner** [comment]
@ricky001 
Any update on this?

**Comment by gmessner** [comment]
@ricky001 
Closing as a non-issue, if you would like to reopen it with additional info, please do.
