### ISSUE TITLE
Don't use String for password parameters

### ISSUE THREAD

**Issue by augi** [gmessner/gitlab4j-api#155]
To lower the potential attack surface, it's recommended not to use `String` to store sensitive data. So I propose to use `CharSequence` for `password` parameters (e.g in `GitLabApi.login` method). We could use implementation like [this](https://github.com/OWASP/passfault/blob/master/core/src/main/java/org/owasp/passfault/impl/SecureString.java). It allows to clear the underlying char array after the sensitive information is not needed.

I'm not creating PR because I'm not sure if the underlying HTTP library is able to handle this. The point is that the `CharSequence` cannot be converted to `String` at any time - it would break the concept.

If you point me to the right direction, I'm ready to create a new PR.

**Comment by gmessner** [comment]
I have a mechanism for doing this.  Two questions though:

1. I'm thinking that a SecureString implementation should be provided so that the consumer can easily create a CharSequence, and then use CharSequence as the type of parameter passed to the login method, or should the type be SecusreString, so that a String (implements CharSequence) cannot be passed in?

2. I will only be implementing this for oauth2Login(), the login() methods will be deprecated as GitLab no longer supports session login, and when login() fails it actually uses oauth2Login() anyways.  See any issues with this?

**Comment by augi** [comment]
1. That's actually great question! And little bit tricky :) Accepting `CharSequence` (so accepting also plain `String`) doesn't break backward compatibility and works seamlessly for users that don't care about security. On other hand, accepting `SecureString` indicates that this library takes care about security and that the value is not _leaked_ internally (never instantiates a `String` from `SecureString`). So I would probably prefer to accept `SecureString` only as the method argument.
2. Sure, that's no problem IMHO. It doesn't make sense to invest time to something that is deprecated.

**Comment by gmessner** [comment]
@augi 
I've actually finished the implementation.  I ended up not restricting it to the secure String implementation I created (SecretString), and it also accepts char[].  If you would like to take a look I've added a PR:

https://github.com/gmessner/gitlab4j-api/pull/157

**Comment by augi** [comment]
That's great, thanks!

Btw. it would be nice to allow to pass also `token` as `char[]`, like in [this constructor](https://github.com/gmessner/gitlab4j-api/blob/master/src/main/java/org/gitlab4j/api/GitLabApi.java#L318). Of course, it makes sense only if the token is required for connection initialization. If the token is required for all the requests then it wouldn't make sense.

**Comment by gmessner** [comment]
Unfortunately, the token is required in a header on each and every request.

**Comment by gmessner** [comment]
@augi 
PR #157 for this has been merged.

**Comment by augi** [comment]
Great, thank you!
