### ISSUE TITLE
A conflicting JAR ?

### ISSUE THREAD

**Issue by gtardivo** [gmessner/gitlab4j-api#160]
Hello! 
I am trying to use gitlab4j-api, but i'm stuck with the exception above:

Exception in thread "main" java.lang.NoSuchFieldError: SNAKE_CASE
	at org.gitlab4j.api.utils.JacksonJson.<init>(JacksonJson.java:61)
	at org.gitlab4j.api.Pager.<clinit>(Pager.java:54)
	at org.gitlab4j.api.ProjectApi.getProjects(ProjectApi.java:94)
	at br.com.bb.alm.gitlabtesteapi.funcoes.ListarProjetos.listaProjetos(ListarProjetos.java:15)
	at br.com.bb.alm.gitlabtesteapi.main.AppRun.main(AppRun.java:13)

This are my External Libraries:

Maven: com.fasterxml.jackson.core:jackson-annotations:2.4.1
Maven: com.fasterxml.jackson.core:jackson-core:2.4.1
Maven: com.fasterxml.jackson.core:jackson-databind:2.4.1
Maven: com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.4.1
Maven: com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:2.9.3
Maven: com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:2.9.3
Maven: com.fasterxml.jackson.jaxrs:jackson-jaxrs-xml-provider:2.4.1
Maven: com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.9.3
Maven: com.google.code.gson:gson:2.6.2
Maven: com.sun.activation:javax.activation:1.2.0
Maven: javax.annotation:javax.annotation-api:1.2
Maven: javax.inject:javax.inject:1
Maven: javax.servlet:javax.servlet-api:3.1.0
Maven: javax.ws.rs:javax.ws.rs-api:2.1
Maven: javax.xml.bind:jaxb-api:2.3.0
Maven: javax.xml.stream:stax-api:1.0-2
Maven: org.apache.httpcomponents:httpclient:4.5
Maven: org.codehaus.woodstox:stax2-api:3.1.1
Maven: org.codehaus.woodstox:woodstox-core-asl:4.1.4
Maven: org.gitlab4j:gitlab4j-api:4.8.7
Maven: org.glassfish.hk2.external:aopalliance-repackaged:2.5.0-b42
Maven: org.glassfish.hk2.external:javax.inject:2.5.0-b42
Maven: org.glassfish.hk2:hk2-api:2.5.0-b42
Maven: org.glassfish.hk2:hk2-locator:2.5.0-b42
Maven: org.glassfish.hk2:hk2-utils:2.5.0-b42
Maven: org.glassfish.hk2:osgi-resource-locator:1.0.1
Maven: org.glassfish.jersey.connectors:jersey-apache-connector:2.26
Maven: org.glassfish.jersey.core:jersey-client:2.26
Maven: org.glassfish.jersey.core:jersey-common:2.26
Maven: org.glassfish.jersey.inject:jersey-hk2:2.26
Maven: org.hamcrest:hamcrest-core:1.3
Maven: org.javassist:javassist:3.22.0-CR2

Do you think that its a conflict due to JAX RS v2 (which GitLab4J uses)?

Thanks in advance for all the help and support!

Also congratulations for this great api!

**Comment by gmessner** [comment]
The conflict is with the `2.4.1` Jackson jars you are using, all the Jackson jars should be `2.9.3`
The 2.4.1 jars are nearly 4 years old.
