### ISSUE TITLE
Lfs File upload break

### ISSUE THREAD

**Issue by jflefebvre06** [gmessner/gitlab4j-api#161]
Hello,

When I try to upload a LFS file, I get the belowed error :
GitLab: LFS objects are missing. Ensure LFS is properly set up or try a manual "git lfs push --all".

Any idea?

**Comment by gmessner** [comment]
@jflefebvre06 
What method are you using from GitLab4J to upload the LFS file?

**Comment by gmessner** [comment]
@jflefebvre06 
You are using the API correctly, however, the GitLab API does support LFS files, you need to use the git-lfs extension.  I did find a Java project that does git-lfs, I don't know how well it works though:

https://github.com/bozaro/git-lfs-java

**Comment by jflefebvre06** [comment]
OK thank you

**Comment by gmessner** [comment]
I'm going to close this, if you need to re-open it for further help, please do.

**Comment by jflefebvre06** [comment]
Hello @gmessner and thanks for your fast reply.

The issue should be trated by the gatlab team : https://gitlab.com/gitlab-org/gitlab-ce/issues/44613
