### ISSUE TITLE
Support for "Closed At" for issues

### ISSUE THREAD

**Issue by bcparkison** [gmessner/gitlab4j-api#164]
The GitLab API for Issues has a "closed_at" field, which is very useful for finding issues closed in a certain period of time.

https://docs.gitlab.com/ee/api/issues.html

Could support for that field please be added to this API?  Thanks!

**Comment by gmessner** [comment]
@bcparkison 
Yes, we can add support for it.  I expect a new release by the end of the week and will include this fields.

**Comment by gmessner** [comment]
Support for the issues closed_at property has been added in the just released 4.8.8
