### ISSUE TITLE
Not displaying the all members of the project

### ISSUE THREAD

**Issue by ricky001** [gmessner/gitlab4j-api#165]
While executing the below code, we didn't get all the members of the project, Why is it happening

Pager<Project> projects=gitLabApi.getProjectApi().getMemberProjects(50);
				while(projects.hasNext())
				{
					List<Project> projectss=projects.next();
					for(Project project:projectss)
					{
						Pager<Member> members=gitLabApi.getProjectApi().getMembers(project.getId(), 85);
						while(members.hasNext())
						{
							List<Member> memberss=members.next();
							for(Member member:memberss)
							{
								System.out.println(i+" "+project.getNameWithNamespace()+" "+member.getName()+" "+member.getAccessLevel().toValue().intValue());
							}
						}
						
					i++;
					}
					
				}

**Comment by gmessner** [comment]
@ricky001 
Per the documentation at: 
https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project

This call only returns members that are **viewable by the authenticated user**.  I could find no information on what makes a member `viewable`, that is a question to be asked of GitLab.

If you made this call with a user that had a higher access level (MASTER) I'm certain all the members would be returned.

**Comment by gmessner** [comment]
@ricky001 
Can this issue be closed?
