### ISSUE TITLE
Too many request

### ISSUE THREAD

**Issue by ricky001** [gmessner/gitlab4j-api#170]
While running the script the below error occurs.
org.gitlab4j.api.GitLabApiException: Too Many Requests.
It does not occur earlier, but form today it occurring very frequently. What can be the possible reason for this error.

**Comment by gmessner** [comment]
If you are using gitlab.com it enforces rate limits.  We use to run the gitlab4j unit tests against gitlab.com, but often ran into the same rate limits and the tests would fail.  We now use an internal GitLab server running in docker to run the unit tests.

**Comment by gmessner** [comment]
@ricky001 
Can this be closed?

**Comment by gmessner** [comment]
@ricky001 
I hadn't heard back, so went ahead and closed this issue, you can always re-open if needed.

**Comment by ricky001** [comment]
@gmessner  what is the limit imposed by GitLab.com, since we are using GitLab Enterprise still the issue come, Is there any way to overcome this issue

**Comment by gmessner** [comment]
@ricky001 
I have no idea, you need to reach out to GitLab support and ask them.  They might have a mechanism to increase it.
