### ISSUE TITLE
Services API "JIRA"

### ISSUE THREAD

**Issue by mind-blowing** [gmessner/gitlab4j-api#175]
Can you please implement "JIRA" service management.
https://docs.gitlab.com/ee/api/services.html#jira

**Comment by gmessner** [comment]
@mind-blowing 
I've made the initial commit of the mods to support JIRA. I still need to add unit tests before doing an official release, should happen in the next day or two.

In the process of implementing the JIRA and Slack support, I discovered a handful of bugs with the GitLab API itself, I will be filling issues with GitLab and report those issue numbers back here.

**Comment by gmessner** [comment]
@mind-blowing
GitLab4J Release 4.8.14 has been released with support for configuring/managing the JIRA integration service.

There are a couple of bugs that I need to report to GitLab:
1) configuring trigger on "Merge request" via the API has no effect, works fine when setting in the UI. Trigger on "Commit" works fine.
2) The project_key parameter is apparently supported in the API but the UI does not allow it to be set.
3) There is also in no indication in the response from the API call whether the project_key value was applied.

**Comment by mind-blowing** [comment]
Thanks a lot.
