### ISSUE TITLE
Services API "Slack notifications"

### ISSUE THREAD

**Issue by mind-blowing** [gmessner/gitlab4j-api#176]
Can you please implement "Slack notifications" service management.
https://docs.gitlab.com/ee/api/services.html#slack-notifications

**Comment by gmessner** [comment]
@mind-blowing 
I've made the initial commit of the mods to support Slack Notifications. I still need to add unit tests before doing an official release, should happen in the next day or two.

**Comment by mind-blowing** [comment]
Thanks a lot, it works.
