### ISSUE TITLE
Unable to get Author & Assignee emailId from MergeRequest

### ISSUE THREAD

**Issue by rkskarthik** [gmessner/gitlab4j-api#178]
Hi @gmessner 

I am simply parsing MR's and try to get needed details.below is my code. 

///
GitLabApi gitLabApi = new GitLabApi(GIT_URL, GIT_AUTHTOKEN);
List<MergeRequest> mergeRequests = gitLabApi.getMergeRequestApi().
				getMergeRequests(GIT_PROJECT_ID, MergeRequestState.OPENED);
///

And I am trying to get the Author&Assignee email id from Single MR like below.

obj.put("author_name", mergeRequest.getAuthor().getName());
obj.put("author_email", mergeRequest.getAuthor().getEmail());
obj.put("assignee", mergeRequest.getAssignee().getName());
obj.put("assignee_email", mergeRequest.getAssignee().getEmail());

But for both email id, it's returning the NULL value.

Please correct me if am doing anything wrong.

**Comment by gmessner** [comment]
I have tested the GitLab API using Postman and it appears that it no longer includes the email address in the response,  GitLab4J only populates the objects with the data from the response.

You can manually validate what your server is returning by using Postman and going at the following URL:

```
{GIT_URL}/api/v4/projects/{GIT_PROJECT_ID}/merge_requests
```

You'll need to add the following HTTP headers when doing it manually:
```
PRIVATE-TOKEN = {GIT_AUTHTOKEN]
Accept = application/json
```

**Comment by rkskarthik** [comment]
@gmessner Thanks for the correction 👍 . I found that Gitlab doesn't provide both email values in the response. Hence, I will close the issue.
