### ISSUE TITLE
Repositories contributors cannot be retrieved

### ISSUE THREAD

**Issue by ISibboI** [gmessner/gitlab4j-api#180]
The api seems to be missing a method to retrieve a projects contributors, using this call:

https://docs.gitlab.com/ee/api/repositories.html#contributors

Is there any reason for that? Otherwise I'd just create a pull request.

**Comment by gmessner** [comment]
This is a relatively new endpoint.  If you'd like to create a PR that would be great.

If you are unable to submit a PR, I can get this added and released in the next release of GitLab4J which is scheduled for 5/7/2018.

**Comment by ISibboI** [comment]
Awesome! I will probably add multiple features since I need this library for a company project, and it is a great foundation.

**Comment by gmessner** [comment]
@ISibboI 
Are you still planning on creating a PR with your enhancements, or should I go ahead and implement this specific one?

**Comment by gmessner** [comment]
@ISibboI 
Thanks for contributing the enhancement.
