### ISSUE TITLE
Adding new functionality

### ISSUE THREAD

**Issue by aleks-programmer** [gmessner/gitlab4j-api#187]
Please add functionality to find merge requests by author_id and other parameters.
It would be great to find by parameters because in GitLab API it is implemented
https://docs.gitlab.com/ee/api/merge_requests.html#list-merge-requests

**Comment by mitarcon** [comment]
@gmessner I can help with this. Do you have any problem?

**Comment by gmessner** [comment]
@mitarcon 
I just have not had time to implement this.  If you would like to implement and submit a PR, I would be happy to review it.

**Comment by gmessner** [comment]
@aleks-programmer @mitarcon 
Support for filtering merge requests has been added.  Use this functionality, as follows:
```
MergeRequestFilter filter = new MergeRequestFilter()
    .withAuthorId(anAuthorId)
    .withTargetBranch("master");
    Pager<MergeRequest> pager =  gitLabApi.getMergeRequestApi().getMergeRequests(filter, 20);
```

All of the possible filter parameters are supported, with fluent methods.  See the MergeRequestFilter class for the available `withXYZ()` methods.
