### ISSUE TITLE
not getting connection using private token 

### ISSUE THREAD

**Issue by KMadhuSudhan** [gmessner/gitlab4j-api#188]
Below statement does not give any results , its getting struct here only
GitLabApi gitLabApi = new GitLabApi(ApiVersion.V3, "http://your.gitlab.server.com", "YOUR_PRIVATE_TOKEN");

**Comment by gmessner** [comment]
Not understanding your issue, this statement does nothing but allocate an object.  Is it throwing an exception, if so please provide the stack trace.

**Comment by gmessner** [comment]
@KMadhuSudhan 
Additionally, if you have not, you need to replace  "http://your.gitlab.server.com" and "YOUR_PRIVATE_TOKEN" with your values.

**Comment by shuklaalok7** [comment]
@KMadhuSudhan if you are still facing this issue, I can help you. If not, we can close this issue.

**Comment by gmessner** [comment]
@KMadhuSudhan 
Have you resolved this issue, if so, please close.

**Comment by gmessner** [comment]
@KMadhuSudhan 
I am closing this issue, if you need to re-open it, please feel free to do so.
