### ISSUE TITLE
Gitlab API v4

### ISSUE THREAD

**Issue by Ezor** [gmessner/gitlab4j-api#19]
Hi, 

The project is currently using the v3 of the Gitlab API. The v3 is deprecated and may be removed in Gitlab 9.4 : https://docs.gitlab.com/ce/api/v3_to_v4.html#v3-to-v4-version

Did you planned to move to the v4 API ?

**Comment by gmessner** [comment]
GitLab4J-API will support v4 in the very near future (within the next few weeks).  The intent is to concurrently support both V3 and V4, the version would be selected when an instance of GitLabApi is created.

I will leave this issue open until V4 support has been added.

**Comment by Ezor** [comment]
That's a great news, thanks for this amazing work

**Comment by gmessner** [comment]
Completed initial support for GitLab API V4.
