### ISSUE TITLE
API to get MR's specific to the Target branch

### ISSUE THREAD

**Issue by rkskarthik** [gmessner/gitlab4j-api#193]
Can we have the option/API to get Merge Requests which are specific to the Target branch?

**Comment by gmessner** [comment]
@rkskarthik 
Support for filtering merge requests has been added. Use this functionality as follows:

```
MergeRequestFilter filter = new MergeRequestFilter()
    .withTargetBranch("master");
Pager<MergeRequest> pager =  gitLabApi.getMergeRequestApi().getMergeRequests(filter, 20);
````
All of the possible filter parameters are supported, with fluent methods. See the MergeRequestFilter class for the available withXYZ() methods.

**Comment by rkskarthik** [comment]
thanks for providing the support :) @gmessner
