### ISSUE TITLE
Hello! Is there an api to star a project?

### ISSUE THREAD

**Issue by zhengrenjie** [gmessner/gitlab4j-api#194]
Hello! Is there an api to star a project?
I have checking out many apis like ProjectApi, RepositoryApi, UserApi etc. and have used the search function in Chrome.But not found. 
Star a project may be a important and basic function for git~~~        ^_^

**Comment by gmessner** [comment]
The star and unstar calls are not yet implemented.  Will add these in the next release, which should be complete by 6/11/2018.  Will notify you when the release has been made.

**Comment by gmessner** [comment]
@zhengrenjie 
starProject() and unstarProject() have been added and released in 4.8.22.
