### ISSUE TITLE
Gitlab renames Master to Maintainer

### ISSUE THREAD

**Issue by jgoldhammer** [gmessner/gitlab4j-api#198]
In gitlab release 11 gitlab will rename the Master access level to Maintainer.

![image](https://user-images.githubusercontent.com/3872101/41396031-feabee76-6faf-11e8-9c68-83e8f4be387b.png)

https://gitlab.com/gitlab-com/www-gitlab-com/blob/release-11-0/source/images/11_0/master-to-maintainer.png

See the discussion here:
https://gitlab.com/gitlab-org/gitlab-ce/issues/42751

Can we provide a PR for this?

**Comment by gmessner** [comment]
@jgoldhammer 
MAINTAINER access level has been added and MASTER has been deprecated. The changes have been merged with the master branch but an official release has not been done,  will do a release when there are additional fixes/updates to release.

**Comment by gmessner** [comment]
This has been released in 4.8.25.
