### ISSUE TITLE
Getting Bad Request, possibly due to Date.toString

### ISSUE THREAD

**Issue by nafg** [gmessner/gitlab4j-api#202]
I'm getting a 400 error while trying to create an issue. This is my theory as to the cause:

IssuesApi.java line 219 passes createdAt and dueDate to withParam, which toStrings it, which results in values like `Sun Feb 10 05:22:13 EST 2013`, however https://docs.gitlab.com/ee/api/issues.html#new-issue says it has to be in ISO 8601.

**Comment by nafg** [comment]
Here is a screenshot from the debugger while inside `createIssue`, showing the value of each parameter:
![image](https://user-images.githubusercontent.com/98384/41928156-46a5da8e-7942-11e8-9d16-987ed3204b26.png)

I don't see where JSON comes in to the picture since it's sending it as a GitLabApiForm, form-encoded POST body. The `toString` that I mentioned is here: https://github.com/gmessner/gitlab4j-api/blob/master/src/main/java/org/gitlab4j/api/GitLabApiForm.java#L51

Thanks.

**Comment by nafg** [comment]
Note that TestIssuesApi only (AFAICT) tests the 3-parameter overload of createIssue, so createdAt would be `null`, thus not testing the `toString` behavior mentioned.

**Comment by nafg** [comment]
assigneeIds would be a similar issue. I'm not even sure how gitlab wants it to be formatted.

**Comment by zhengrenjie** [comment]
[Date time string, ISO 8601 formatted, e.g. 2016-03-11T03:45:40Z (requires admin or project owner rights)](https://docs.gitlab.com/ce/api/issues.html#new-issue) have a try!

**Comment by gmessner** [comment]
@nafg 
You are correct, thanks for pointing this out.  `withParam()` has been overloaded to handle both Date and List types correctly.  I've also added a test for `createIssue()` with both createdAt and assigneeIds parameters set.

I've released version 4.8.26 with the fix, please verify and close this when you have a chance.

**Comment by nafg** [comment]
I was using it to import my tickets from youtrack, and in the end I just used an http library, so I don't have what to try it with anymore.

However, the code looks good, plus it has a test, so I would assume it's solved.

(P.S. Since you're requiring Java 8, you could use java.time to do ISO-8601. Similarly, there are better types than java.util.Date. In fact, if createdAt was a java.time.Instant and dueDate was a java.time.LocalDate, arguably the most fitting types, then `.toString()` _would_ be the right format. But of course, that's a breaking change, or at least an API change, which is a separate discussion...)

**Comment by gmessner** [comment]
In reference to the use of java.time and changing to something other than Date.  The ISO8601 formats used by GitLab are not always sensible and the ISO8601 class included in GitLab4J handles those insensibilities. Switching to another class for date types would be a problem with the consumers of this library, so there is really no benefit in doing so.

Do appreciate the suggestions though.
