### ISSUE TITLE
Gitlab delete group break

### ISSUE THREAD

**Issue by jflefebvre06** [gmessner/gitlab4j-api#203]
Hello,

I have swith today to Gitlab 11.0.1 and the "Remove group" failed because previously return a 200 and now return a 202

> The response will be a 202 Accepted if the user has authorization

**Comment by gmessner** [comment]
@jflefebvre06 
This has been fixed and released in version 4.8.26, please verify and close when you have a chance.

**Comment by jflefebvre06** [comment]
Works find thanks a lot
