### ISSUE TITLE
Missing Attributes in Update Merge Request API

### ISSUE THREAD

**Issue by armsnyder** [gmessner/gitlab4j-api#205]
There are a number of attributes in the Update Merge Request API which cannot be set using the existing parameters of the MergeRequestApi#updateMergeRequest method.

The full list of accepted attributes can be found here:
https://docs.gitlab.com/ee/api/merge_requests.html#update-mr

**Comment by gmessner** [comment]
@armsnyder 
Please see my comments on the PR you submitted.

**Comment by gmessner** [comment]
@armsnyder 
Your PR has been released ibn release 4.8.27.  Thanks again for your contribution.

**Comment by armsnyder** [comment]
@gmessner Thanks for the fast turnaround!
