### ISSUE TITLE
Filtering of Merge Request by date wise

### ISSUE THREAD

**Issue by ricky001** [gmessner/gitlab4j-api#212]
There is no function in the jar from which we can filter the merge request based on date.
But in GitLab API https://docs.gitlab.com/ee/api/merge_requests.html we can filter based on created_after or created_before or updated_after or updated_before.

How can we filter the merge request based on date wise?

**Comment by gmessner** [comment]
Use the `getMergeRequests()` methods that take an instance of `MergeRequestFilter`:
```
public List<MergeRequest> getMergeRequests(MergeRequestFilter filter) 
public List<MergeRequest> getMergeRequests(MergeRequestFilter filter, int page, int perPage)
public Pager<MergeRequest> getMergeRequests(MergeRequestFilter filter, int itemsPerPage) 
```
You can specify the dates in the filter as follows:
```
MergeRequestFilter filter = new MergeRequestFilter()
    .withUpdatedAfter(ISO8601.toDate("2018-07-02")
    .withUpdatedBefore(ISO8601.toDate("2018-07-05");
```

**Comment by ricky001** [comment]
@gmessner Not able to find below methods in jar 4.8.8 or 4.8.3

public List<MergeRequest> getMergeRequests(MergeRequestFilter filter) 
public List<MergeRequest> getMergeRequests(MergeRequestFilter filter, int page, int perPage)
public Pager<MergeRequest> getMergeRequests(MergeRequestFilter filter, int itemsPerPage)

**Comment by gmessner** [comment]
@ricky001 
These methods where added in release 4.8.21, my appologies for not mentioning that.

**Comment by tricharu** [comment]
@gmessner  The below method does not provide to filter the merge request of a single project

**Comment by tricharu** [comment]
MergeRequestFilter filter = new MergeRequestFilter()
			    .withUpdatedAfter(ISO8601.toDate("2018-05-31"))
			    .withUpdatedBefore(ISO8601.toDate("2018-07-01"))
			    ;
		
		List<Project> projects=gitLabApi.getProjectApi().getProjects("sample-bots");
		
		//for(Project project:projects)
		{
			Pager<MergeRequest> merges=gitLabApi.getMergeRequestApi().getMergeRequests(filter, 50);
			while(merges.hasNext())
			{
				List<MergeRequest> merge=merges.next();
				for(MergeRequest merg:merge)
				{
					System.out.println(merg.getMergeStatus()+","+merg.getDescription());
				}
				
			}
		}

**Comment by gmessner** [comment]
@tricharu 
Support for filtering by project and merge request IID has been added and is available in release 4.8.34

You'll find 2 new properties that can be set on the MergeRequestFilter:
```
.withProjectId(Integer projectId)
.withIids(List<Integer> mergeRequestIids)
```

**Comment by gmessner** [comment]
@tricharu 
I overlooked adding the withProjectId() and withIids() methods, I have added them but they are not available in the 4.8.34 release, you'll need to use the following until 4.8.35 is released:
```
filter.setProjectId(Integer projectId)
filter.setIids(List<Integer> mergeRequestIids)
```

**Comment by tricharu** [comment]
@gmessner  Thanks for the updates....
if we want to get the line comments in merge request not the conversation how to get that part

**Comment by gmessner** [comment]
@tricharu 
I believe the following methods on the ```NotesApi``` are what you are looking for:
```
public List<Note> getMergeRequestNotes(Integer projectId, Integer mergeRequestIid) 
public List<Note> getMergeRequestNotes(Integer projectId, Integer mergeRequestIid, SortOrder sortOrder, Note.OrderBy orderBy)
public List<Note> getMergeRequestNotes(Integer projectId, Integer mergeRequestIid, int page, int perPage)
public List<Note> getMergeRequestNotes(Integer projectId, Integer mergeRequestIid, SortOrder sortOrder, Note.OrderBy orderBy, int page, int perPage)
public Pager<Note> getMergeRequestNotes(Integer projectId, Integer mergeRequestIid, int itemsPerPage)
public Pager<Note> getMergeRequestNotes(Integer projectId, Integer mergeRequestIid, SortOrder sortOrder, Note.OrderBy orderBy, int itemsPerPage)
public Note getMergeRequestNote(Integer projectId, Integer mergeRequestIid, Integer noteId) 
```

**Comment by aikamyx2004** [comment]
will be available such filters for users with parameters from https://docs.gitlab.com/api/users/? 

smth like:

``` 
public List getUsers(UserFilter filter)
```
