### ISSUE TITLE
Dropping API v3 support

### ISSUE THREAD

**Issue by shuklaalok7** [gmessner/gitlab4j-api#213]
This issue is opened to discuss the support for API v3 in this library. Support for API v3 was removed in GitLab 11.0.

See, https://docs.gitlab.com/ee/api/v3_to_v4.html

**Comment by gmessner** [comment]
There are many still using GitLab < 11.0, and since library defaults to API v4, and the consumer must explicitly specify API v3, there is no compelling reason to drop support for v3 just yet.

**Comment by gmessner** [comment]
@shuklaalok7 
I am going to close this issue.  That being said, I have put something on my calendar to remove support for v3 the first part of 2019.  I added info to the README.md file alerting people of this pending change.  This will give a warning and some time to anyone using the V3 to make the change.
