### ISSUE TITLE
AwardEmoji API

### ISSUE THREAD

**Issue by shuklaalok7** [gmessner/gitlab4j-api#214]
This library lacks support for [Award Emoji API](https://docs.gitlab.com/ee/api/award_emoji.html). I know that this may not be the very much needed feature but this issue is added to remind that it needs to be added.
I may open a PR to add this API.

**Comment by gmessner** [comment]
@shuklaalok7 
The AwardEmojiApi is available in release 4.8.30.  I didn't have time to create tests for this, will do so when I have some more time.  I am leaving this issue open just in case you find any bugs.

**Comment by gmessner** [comment]
@shuklaalok7 
Haven't heard anything back so I assume this is working for you.  I'm closing the issue, you can always reopen it or create another if you find any problems.
