### ISSUE TITLE
How to run api which does not contain main method

### ISSUE THREAD

**Issue by ashu-3** [gmessner/gitlab4j-api#22]
I am new to jgit. I downloaded the zip file of gitlab api but since it doesnot contain main method I am not able to run the api. I had not worked on github before . please provide me steps to run this api. 
Thank you

**Comment by gmessner** [comment]
@ashu-3 
GitLab-4J is a Java library, not a tool, so there is no main method.  It is intended to be used by Java developers to simplify creating applications or tools that work with GitLab servers.
