### ISSUE TITLE
how do i get multiple assignees of an issue

### ISSUE THREAD

**Issue by sbchowrasia** [gmessner/gitlab4j-api#220]
![image](https://user-images.githubusercontent.com/41003198/42450455-da93eede-83a1-11e8-8bbe-17e2a53f3693.png)

  
the above function gets the name of only first assigned user.
please help me.

**Comment by gmessner** [comment]
@sbchowrasia 
The latest version (4.8.30) of this library has added the assignees property to the issue class. With this new version simply call `getAssignees()` on the issue to get the list of assignees.

**Comment by sbchowrasia** [comment]
Hey @gmessner thank you, It worked like a charm. :)
