### ISSUE TITLE
enable logging of http requests/responses

### ISSUE THREAD

**Issue by jgoldhammer** [gmessner/gitlab4j-api#228]
It would be nice if gitlab4j supports logging http requests and responses via Jersey. 
It would allow to inspect the messages transferred to the gitlab server.

**Comment by gmessner** [comment]
@jgoldhammer 
I temporarily added you as a collaborator so you could review and merge the PR when you are ready. Here is the PR:
https://github.com/gmessner/gitlab4j-api/pull/229

**Comment by jgoldhammer** [comment]
Thanks. I have merged it, very well done!
Can you upload this as new version to Maven Central ?
