### ISSUE TITLE
Create pipeline doesn't work as expected

### ISSUE THREAD

**Issue by mstekel** [gmessner/gitlab4j-api#230]
Hi,

I'm using gitlab4j 4.8.39.

Calling gitLabApi.getPipelineApi().createPipeline(project.getId(), branch.getName()) sends a POST request to  http://<base_url>/api/v4/projects/<project_id>/pipelines?ref=branch while it's supposed to send it to http://<base_url>/api/v4/projects/<project_id>/**pipeline**?ref=branch.

I know that it's weird from Gitlab side to expect a single entity URL for POST requests but it's what they expect (review their API docs). Changing the entity from plural to single fixes the issue otherwise HTTP 404 is returned. Please fix.

Moshe.

**Comment by gmessner** [comment]
@mstekel 
You've discovered a bug with the GitLab API itself, they use the plural form everywhere else except in this one instance.  I'll fix it in this library and will look into submitting a bug report with GitLab.

I will let you know when the fix is released, should be today.

**Comment by mstekel** [comment]
Thank you. Please make the fix available via maven.

**Comment by gmessner** [comment]
@mstekel 
I've already completed the full release, though sometimes it takes about 24 hours to propagate thru to all the repos.

**Comment by mstekel** [comment]
Great!!! Thank you!!!

**Comment by gmessner** [comment]
@mstekel 
When you get a chance, could you verify and close this issue?

**Comment by mstekel** [comment]
Fixed. Thanks.
