### ISSUE TITLE
WebHookManager can not managed the WebHook request URL.

### ISSUE THREAD

**Issue by Hyzhou** [gmessner/gitlab4j-api#238]
Event do not contain the request URL.
So the Listener can not get the parameters in the callback URL.

**Comment by gmessner** [comment]
@Hyzhou 
I would propose that the following properties be added to ```org.gitlab4j.api.systemhooks.SystemHookEvent``` and  ```org.gitlab4j.api.webhook.Event```:
```
String getRequestUrl()
String getRequestQueryString()
```
These values would be pulled from the ```HttpServletRequest```

Does this meet your needs?

**Comment by Hyzhou** [comment]
@gmessner  that is great! waitting for the release.

**Comment by gmessner** [comment]
@Hyzhou 
I've released version 4.8.42 with the ```getRequestUrl()``` and ```getRequestQueryString()``` methods added to the event interfaces and implementations.

If this meets your needs, please verify and close this issue.

**Comment by Hyzhou** [comment]
@gmessner Thank you. I will try to test it now. wait me for the response of the issue. :)

**Comment by gmessner** [comment]
@Hyzhou 
Any update on this?

**Comment by Hyzhou** [comment]
@gmessner sorry, I allready test it, It works well.
