### ISSUE TITLE
RepositoryFile update content, how?

### ISSUE THREAD

**Issue by Spenhouet** [gmessner/gitlab4j-api#240]
I want to update the content of a file in the repository.

I tried the official API command with postman:

```
PUT /projects/:id/repository/files/:file_path?branch=master
                                                &author_email=author%40example.com
                                                &content=some%20other%20content
                                                &commit_message=update%20file
```

https://docs.gitlab.com/ee/api/repository_files.html

and that works perfectly.

With this I can just input the new file content as urlencoded string with

`content=new%20content`

I tried to update the content of a file in the repository with the `updateFile` method from the `RepositoryFileAPI`.

For that I retrieved the existing README file content with

`repositoryFileApi.getOptionalFile(...).getContent()` 

but that doesn't give the expected output.
I guess I have to use `repositoryFileApi.getRawFile()` for that.

But how to set the new content?

I tried with `repositoryFile.setContent(newContent)` followed by `updateFile` but the new file content in the repository is not readable. Just looks like random symbols and is way to short. My first thought was that it is a encoding issue but I'm not sure if setting `repositoryFile.content` even is the right thing to do in the first place since `getContent` already didn't return the raw document content.

Is there a easy way to just do the above PUT from the official documentation to update the content of a repository file?

**Comment by Spenhouet** [comment]
It seems to be a other issue. Urlencoding the string doesn't help (in contrary, it gets worse).

This somewhat doesn't do what I expected.

`repositoryFileApi.getOptionalFile(...).getContent()` doesn't return the raw content of the file.

What I would like to do is to get the current content of the README file and then to update the README file with a added line.

This should be possible with: `GET /projects/:id/repository/files/:file_path/raw?ref=master`
And `PUT /projects/:id/repository/files/:file_path?branch=master&author_email=author%40example.com&content=some%20other%20content&commit_message=update%20file'`

https://docs.gitlab.com/ee/api/repository_files.html

I tested both official API endpoints with Postman and it works as expected.
How can I do the same with the Java API?
Is this implemented?

**Comment by gmessner** [comment]
@Spenhouet 
The example provided by GitLab is not a good example.  It is not a good idea to be passing the content in as a query param, it should be included in the body of the request.

When you set the content as a plain text String before calling ```updateFile()``` you must also set the encoding to "text" as follows: ```file.setEncoding("text")```

When you fetch the RepositoryFile instance using ```getOptionalFile(...)``` or ```getFile(...)``` the content is Base64 encoded so you'll need to do the following to decode it:
```
RepositoryFile file = gitLabApi.getRepositoryFileApi().getFile("file-path", projectID, "master");   
byte[] fileContents = java.util.Base64.getDecoder().decode(file.getContent());
```
I have added some convenience methods to ```RepositoryFile``` to simplify all the above:
```
public String getDecodedContentAsString()
public byte[] getDecodedContentAsBytes()
public void encodeAndSetContent(String content)
public void encodeAndSetContent(byte[] byteContent)
```

**Comment by jgoldhammer** [comment]
I guess the commit api works better in this case to upload files...

**Comment by Spenhouet** [comment]
@gmessner Yes, it works as expected. Nice addition and quality of life improvement.
