### ISSUE TITLE
There is no way to download the artifact archive of a failed job.

### ISSUE THREAD

**Issue by mstekel** [gmessner/gitlab4j-api#241]
The JobApi::downloadArtifactsFile method uses job name and not job id that obviously means the artifact archive for a successful run of that job name (job name is not unique).
Gitlab API actually provides a method for downloading the artifact archive of any job (by job id):

**GET /projects/:id/jobs/:job_id/artifacts**

but your java wrapper for that API method, Job::getArtifactsFile, returns an instance of ArtifactsFile with only the file name and size - there is no way to access the input stream of the archive.

Please either add a method like `public InputStream getBytes()` to the ArtifactsFile class or provide an overloaded JobApi::downloadArtifactsFile that uses job id (and calls the Gitlab API I mentioned above).

**Comment by gmessner** [comment]
@mstekel 
I just added two methods to JobApi for downloading using the endpoint you referenced:
```GET /projects/:id/jobs/:job_id/artifacts```

They are:
```
// Download the artifacts archive by job ID and save to the specified directory
public File downloadArtifactsFile(Object projectIdOrPath, Integer jobId, File directory)

// Get an InputStream to download the artifacts archive for the specified job ID
public InputStream downloadArtifactsFile(Object projectIdOrPath, Integer jobId)
```

This is available in release 4.8.44, though it might take up to 24 hours for this to be available in the central repos.

**Comment by mstekel** [comment]
Thank you.

**Comment by gmessner** [comment]
@mstekel 
If you could verify and close I would appreciate it.

**Comment by mstekel** [comment]
Not in the repositories yet but I verified it locally. Thanks.
