### ISSUE TITLE
`org.gitlab4j.api.models.Permissions` do not have setter function.

### ISSUE THREAD

**Issue by Hyzhou** [gmessner/gitlab4j-api#243]
The `org.gitlab4j.api.models.Permissions` do not have setter function...
FastJson can not deserialization with it.

**Comment by gmessner** [comment]
@Hyzhou 
This has been fixed and released in 4.8.46. 

Please verify and close when you have an opportunity.  It may take up to 24 hours to be available in the central repositories.

**Comment by Hyzhou** [comment]
yes, this is fixed.
