### ISSUE TITLE
I am not able to get few issues from issues API

### ISSUE THREAD

**Issue by sbchowrasia** [gmessner/gitlab4j-api#247]
Below code snippet is used to get all the issues and its notes:  
```
for (int i = 1; i <= 150; i++) {  
List<Issue> AllIssues = gitLabApi.getIssuesApi().getIssues(p.getId(), i, 20);  
   for (Issue issue : AllIssues) {  
   System.out.println("Issue no: " + issue.getIid());  
   //some code which gets the issue items, such as notes  
   }  
}
```  
Most probable root cause: The issue which was not created in the project, but created on other project and moved to the current project.  
  
Strange is that when i use the Issue number to get that particular issues information, i get that with the same code.  
But in bulk it doesn't return these moved issues.

**Comment by sbchowrasia** [comment]
Sorry False alarm.
Please excuse.

**Comment by gmessner** [comment]
@sbchowrasia 
I know you indicated this was a false alarm, but I wanted to show you a better way of getting all of something, it involves the use of the Pager as follows:
```
Pager<Issue> issuePager = gitLabApi.getIssuesApi().getIssues(p.getId(), 20); 
while (issuePager.hasNext()) {
    for (Issue issue : issuePager.next()) {
        System.out.println("Issue no: " + issue.getIid());  
         // some code which gets the issue items, such as notes
    }
}
```
