### ISSUE TITLE
WebHookManager check X-Gitlab-Event header not exist.

### ISSUE THREAD

**Issue by Hyzhou** [gmessner/gitlab4j-api#248]
When somebody make an callback without X-Gitlab-Event header, There will be an NullPointException.

```
        String eventName = request.getHeader("X-Gitlab-Event");
        LOGGER.info("handleEvent: X-Gitlab-Event=" + eventName);
        switch (eventName) { // NullPointException

        case BuildEvent.BUILD_HOOK_X_GITLAB_EVENT:
        case BuildEvent.JOB_HOOK_X_GITLAB_EVENT:
```

**Comment by gmessner** [comment]
The WebHookManager should only be used to service webhook callouts from a GitLab server, how is it being used that "X-GitLab-Event" header is  not set?

**Comment by Hyzhou** [comment]
@gmessner be attacked.

**Comment by gmessner** [comment]
@Hyzhou 
That makes sense, I'll add a check for the header and simply return if it is not there.  Will do the same for SystemHookManager.

Thanks for reporting this.

**Comment by Hyzhou** [comment]
Thanks

**Comment by gmessner** [comment]
@Hyzhou 
Quick question.  Would you prefer the WebHookManager to throw an exception like:
```
throw new GitLabApiException("X-Gitlab-Event header is missing");
```
Or simply log a warning and return when it is missing?

**Comment by Hyzhou** [comment]
I think simply log was better. Because most of developers do not want to deal with this wrong format callback. If this callback missing header. This callback should always be forged, isn't it? Just log it and ignore it will be better.

**Comment by gmessner** [comment]
@Hyzhou 
If you are satisfied with the fix can you close the issue?

**Comment by Hyzhou** [comment]
Close This Issue
