### ISSUE TITLE
getVersion()  method can't use

### ISSUE THREAD

**Issue by LeafLuo** [gmessner/gitlab4j-api#249]
GitLabApi gitLabApi = new GitLabApi(ApiVersion.V3,"http://your.gitlab.server.com","YOUR_PRIVATE_TOKEN");

When I use gitLabApi.getVersion() ,it cuase
![image](https://user-images.githubusercontent.com/22662589/45400465-c9a57b00-b67e-11e8-8e22-892a9bfb6302.png)

**Comment by gmessner** [comment]
@LeafLuo 
A 401 indicates that your token is invalid or no longer authorized on the GitLab server you specified.

Also, why are you using the V3 API, are you going at an old GitLab server?

**Comment by gmessner** [comment]
@LeafLuo 
Are you still having an issue?  If not, I'd like to close this issue.

**Comment by gmessner** [comment]
@LeafLuo 
I'm going to close this issue.  If you are still having issues please re-open and provide additional info.
