### ISSUE TITLE
org.gitlab4j.api.GitLabApiException: Method Not Allowed

### ISSUE THREAD

**Issue by 402424370** [gmessner/gitlab4j-api#251]
when I used the userApi.blockUser,I get 405 Method Not Allowed.by the way,the gitlab version is 8.5 and used the GitLabApi.ApiVersion.V3.Other function works well.so what's the problem?thanks

**Comment by gmessner** [comment]
@402424370 
You discovered a bug, V3 requires the use of PUT instead of POST, V4 uses POST.  I have made the fix to both blockUser() and unblockUser().  Will let you know when it is released.

**Comment by gmessner** [comment]
@402424370 
4.8.47 has been released, with this fix.  Please verify and close when you have a chance.

It may take up to 24 hours for the release to be in the Maven repos.

**Comment by 402424370** [comment]
ok，thanks for reply so fast
