### ISSUE TITLE
ClassCast-Exception on updating JiraService without TransitionID

### ISSUE THREAD

**Issue by rubenvitt** [gmessner/gitlab4j-api#253]
When I try to update a jiraService without transitionID, the get(...) method throws an ClassCastException, because it tries to convert ""-Value (from JSON) to an Integer.

My work-around for this:
![code](https://user-images.githubusercontent.com/19268519/45534340-0a2a0380-b7fb-11e8-81e8-716d21ee0ec8.PNG)

**Comment by gmessner** [comment]
@rubenvitt 
What is populating the jiraService instance used in your example?

**Comment by gmessner** [comment]
@rubenvitt 
And just to confirm, are using ```gitLabApi.getServicesApi().getJiraService(projectId)``` to get the JiraService instance?

**Comment by rubenvitt** [comment]
Yes, I'm using getJiraService(projectID).
Thanks for the fix!
