### ISSUE TITLE
Need to add detailed error messages in GitlabApiException

### ISSUE THREAD

**Issue by MikaelZulfigarov** [gmessner/gitlab4j-api#254]
Currently, all GitlabApiExceptions that are thrown by the lib only contain an HTTP status code and an error message, which is not really helpful. 

For example, if I receive the GitlabApiException with status "400" and message "Bad Request" I don't know what the actual problem is.

It is even more confusing because the Gitlab API actually returns the correct error description. Like this:
```
{
  "message": "Email has already been taken"
}
```

**Comment by gmessner** [comment]
@MikaelZulfigarov 
GitLabApiException is set up to read the message and set it as the message for the GitLabApiException instance, are you calling getMessage() on the exception to fetch the message?

Also, in the example you provided the GitLab API docs indicate that a 409 should be the status.  See the docs at: https://docs.gitlab.com/ee/api/#status-codes

If you are getting a 400 that implies something else other than "Email has already been taken".  What call were you making when the example exception was thrown, I'd like to test it to see what is going on.

**Comment by gmessner** [comment]
@MikaelZulfigarov 
Can we close this issue?

**Comment by MikaelZulfigarov** [comment]
@gmessner Yeah, I'll share some code to demonstrate the exact case of the issue later

**Comment by gmessner** [comment]
@MikaelZulfigarov 
Changes have been made the ```GitLabApiException``` that should address your problem.  These were done on #260 and released in 4.8.52

Please close this issue if it has been addressed.
