### ISSUE TITLE
getCommits(int projectId, String ref, Date since, Date until) method returned top 100 commits instead of all commits.

### ISSUE THREAD

**Issue by yellowyello** [gmessner/gitlab4j-api#256]
I double checked the gitlab commits history in browser and counted over 200 commits based on Date since and Date until, but in java the size of returned list will not exceed 100. 
The newest commit will be the first element of returned list but the size will remain 100 due to line 89 of CommitsApi.java which called a getDefaultPerPage() method. In GitLabApi.java I found a constant named DEFAULT_PER_PAGE=100.
I wondered how can I bypass this size limit of returned list? I read the comment above constant DEFAULT_PER_PAGE which says GitLab will ignore anything over 100.
Thanks for your time.

**Comment by gmessner** [comment]
You should use:
```
 public Pager<Commit> getCommits(int projectId, String ref, Date since, Date until, int itemsPerPage);
```

The code would look something like:
```
// Get a Pager instance that will page through the commits with 20 commits per page
Pager<Commit> commitPager = gitlabApi.getCommitsApi().getCommits(projectId, ref, since, until, 20);
while (commitPager.hasNext())) {
    for (Commit commit : commitPager.next()) {
        // Do something with the commit
    }
}
```
