### ISSUE TITLE
How to find issues that are closed through merge requests

### ISSUE THREAD

**Issue by siddharthbulia0210** [gmessner/gitlab4j-api#264]
Is there any support for this ?
Gitlab API [link](https://docs.gitlab.com/ee/api/merge_requests.html#list-issues-that-will-close-on-merge). 
@gmessner

**Comment by gmessner** [comment]
@siddharthbulia 
This is fairly new functionality on GitLab so is not yet implemented.  I will be doing a release today and will include this, and will let you know when it is released.

**Comment by gmessner** [comment]
@siddharthbulia 
```getClosesIssues()``` has been added to the ```MergeRequestApi``` in release 4.8.52,  when you have an opportunity, please test and close this issue.

**Comment by siddharthbulia** [comment]
Thank you so much Greg. This is helpful.
You might also want to add support for a related new functionality of gitlab.
[List merge requests that will close issue on merge](https://docs.gitlab.com/ee/api/issues.html#list-merge-requests-that-will-close-issue-on-merge).

**Comment by gmessner** [comment]
@siddharthbulia 
I've merged your PR and released 4.8.53.  Please verify and close this issue when you have a chance.
