### ISSUE TITLE
Is there any support for Discussions API ?

### ISSUE THREAD

**Issue by abhishektiwari2904** [gmessner/gitlab4j-api#267]
Hi,
Is there any support for DiscussionsApi ? Is it similar to notesApi.
API Link - https://docs.gitlab.com/ee/api/discussions.html

**Comment by abhishektiwari2904** [comment]
I will create a pull request to add this feature. :)

**Comment by filippobuletto** [comment]
https://github.com/gmessner/gitlab4j-api/pull/279
