### ISSUE TITLE
List projects of a certain user.

### ISSUE THREAD

**Issue by mlb0029** [gmessner/gitlab4j-api#268]
Hi,
I would like to know if there is any way to list the projects of a certain user. With GitLab API it would be through this line:
`GET /users/:user_id/projects`

https://docs.gitlab.com/ee/api/projects.html#list-user-projects

**Comment by gmessner** [comment]
@mlb0029 
This functionality has been added and just released in version 4.8.54.  The new methods are:
```
public List<Project> getUserProjects(Object userIdOrUsername, ProjectFilter filter)
public List<Project> getUserProjects(Object userIdOrUsername, ProjectFilter filter, int page, int perPage)
public Pager<Project> getUserProjects(Object userIdOrUsername, ProjectFilter filter, int itemsPerPage)
```
