### ISSUE TITLE
Question: Missing equals() and hashCode() implementations

### ISSUE THREAD

**Issue by mdeknowis** [gmessner/gitlab4j-api#271]
Hello,

we stumbled across the fact none of the DTOs are implementing `equals` and `hashCode` (and `toString`).

Currently we are forced to use `org.apache.commons.lang3.builder.ToStringBuilder.reflectionToString(Object)` and `org.mockito.ArgumentMatchers.refEq(T, String...)` etc. to test our code and to generate log output.

So we wonder, if there is a particular reason for that fact?

Regards

**Comment by gmessner** [comment]
@mdeknowis 
For these sorts of classes that are serializing and deserializing JSON toString() methods are not that useful, we provided ```org.gitlab4j.api.utils.JacksonJson.toJsonString()``` so you can simply do this:
```
String s = org.gitlab4j.api.utils.JacksonJson.toJsonString(obj)
```

For comparison, I suggest you look at how we do it in our unit tests, specifically TestGitLabApiBeans.java
I have been thinking about generalizing the comparison code from this and putting it in JacksonJson, if you believe that is a good idea, let me know.

**Comment by mdeknowis** [comment]
Thanks for that `org.gitlab4j.api.utils.JacksonJson.toJsonString()` hint. Currently we try avoid to build `if (log.isDebugEnabled()) {...}` blocks, so we rely on `toString()`. Also in our test we want still to use the advantages of `AbstractObjectAssert` e.g. `org.assertj.core.api.AbstractObjectAssert.isEqualToComparingFieldByFieldRecursively(Object)`, which has more detailed output regarding actual and expected.

**Comment by mdeknowis** [comment]
The issue is also, that frameworks like Mockito use `toString`:

```
Argument(s) are different! Wanted:
org.gitlab4j.api.ProjectApi#0 bean.createProject(
    refEq(org.gitlab4j.api.models.Project@7495699f)
);
-> at my.GitlabProjectServiceTest.testAddProject(GitlabProjectServiceTest.java:202)
Actual invocation has different arguments:
org.gitlab4j.api.ProjectApi#0 bean.createProject(
    org.gitlab4j.api.models.Project@3047254d
);
-> at my.GitlabProjectService.addProject(GitlabProjectService.java:118)

	at my.GitlabProjectServiceTest.testAddProject(GitlabProjectServiceTest.java:202)
...
```

**Comment by mdeknowis** [comment]
Also during debugging, it would be more developer friendly:
![grafik](https://user-images.githubusercontent.com/23213544/48470312-5d1b3980-e7f1-11e8-8944-de30bedccfde.png)

**Comment by gmessner** [comment]
I could agree to support toString() implementations as long as they are using JacksonJson, that would be the only way to guarantee that the results will be accurate.  This is a simple as adding the following ```toString()``` implementation to the model classes:
```
@Override
public String toString() {
    return (org.gitlab4j.api.utils.JacksonJson.toJsonString(this));
}
```

**Comment by mdeknowis** [comment]
Sounds like a good solution for this library.

**Comment by gmessner** [comment]
@mdeknowis 
I've added the ```toString()``` implementation to all the necessary model classes.  This has been released as 4.9.0.  Went ahead and bumped the minor version since this impacted 63 files.   Please verify that this meets your needs and close this issue when you have a chance.

**Comment by gmessner** [comment]
@mdeknowis 
I believe your concerns have been met, so am closing this issue.  Please feel free to open it back up if needed.

**Comment by derekyyyan** [comment]
I ran into this problem as well with mocking, I got around by extending the DTO class and implementing my own `equals()` and `hashCode()`.
Although this will be a substantial change, I think it is valuable to incorporate lombok's `@Data` annotation (https://projectlombok.org/features/Data) into the DTOs, which generates getters, setters, equals, and hashcode all for free.

**Comment by gmessner** [comment]
@derekyyyan 
In the future please open a new issue or reopen a closed one that you are commenting on, as they often get lost when comments are done on closed issues.

I am extremely familiar with Lombok and have used it on many projects, but because of the level of control that is needed and the many oddities with GitLab's JSON formats, it is difficult to have it reliably work.

A better solution would be to use the same type of technology that Lombok does and inject just the ```equals()``` and ```hashCode()``` methods at compile time.  On a different project I have actually wriiten an annotation processor that injects ```toString()```, ```equals()```, and ```hashCode()``` methods at compile time, so have experience with this, and Lombok could be used to only inject ```equals()``` and ```hashCode()```.

Either way, it is a major undertaking and I do not have time in the foreseeable future to do it, my suggestion would be to submit an issue to request adding ```equals()``` and ```hashCode()``` methods to the model classes and I'll get it in the backlog for future implementation.

**Comment by derekyyyan** [comment]
I figured there is a reason the models are implemented the way they are so I hesitated to reopen this issue or create a new one. I still think implementing `equals()` and `hashCode` will make development more intuitive and convenient for library users, so I'll open an issue.

**Comment by jmini** [comment]
See https://github.com/gitlab4j/gitlab4j-api/issues/494
