### ISSUE TITLE
Commit Status API is missing

### ISSUE THREAD

**Issue by roxspring** [gmessner/gitlab4j-api#274]
Looks to me like the Commit Status API is missing:
https://docs.gitlab.com/ee/api/commits.html#commit-status

Am I looking in the wrong place?

**Comment by gmessner** [comment]
@roxspring You are looking in the right place, it is just not implemented yet.  It will be implemented and released with some other updates tomorrow.  Will let you know when it is available.

**Comment by gmessner** [comment]
@roxspring 
This has been released in 4.8.57.  You'll find the ```getCommitStatuses()``` methods in the ```CommitsApi```

Please verify and close when you have a chance.

**Comment by roxspring** [comment]
Awesome!

Thanks for the speedy work! It works perfectly for my current use case, but I have an upcoming use case for the `POST /projects/:id/statuses/:sha` part too... can we get an `addCommitStatus(..)` too?

**Comment by gmessner** [comment]
@roxspring 
I've gone ahead and closed this issue as all support for commit statuses has been added.
