### ISSUE TITLE
Add getOptionalBranch to repositoryApi

### ISSUE THREAD

**Issue by jflefebvre06** [gmessner/gitlab4j-api#281]
Could you please add method `getOptionalBranch`  to the `RepositoryApi` ?

**Comment by gmessner** [comment]
@jflefebvre06 
```RepositoryApi.getOptionalBranch()``` has been added and released in 4.9.2.  Please verify and close when you have an opportunity.

**Comment by jflefebvre06** [comment]
Works fine thank you
