### ISSUE TITLE
getOptionalProject with option statistics

### ISSUE THREAD

**Issue by jflefebvre06** [gmessner/gitlab4j-api#283]
Could you please add method `ProjectApi#getOptionalProject(Object projectIdOrPath, Boolean statistics)`

JF

**Comment by gmessner** [comment]
@jflefebvre06 
This has been added and released in 4.9.4.  Please verify and close when you have time.

BTW, we are in the process of adding methods that provide a Stream instead of a List or Pager to all get methods that produce multiple items.  Currently, only the ProjectApi and DiscussionsApi have had them added, would be great if you could provide feedback on this new feature.  Here are the ones available in
 the ProjectApi:
```
public Stream<Project> getProjectsStream()
public Stream<Project> getProjectsStream(String search)
public Stream<Project> getMemberProjectsStream()
public Stream<Project> getAllProjectsStream()
public Stream<Project> getOwnedProjectsStream()
public Stream<Project> getStarredProjectsStream()
public Stream<ProjectUser> getProjectUsersStream(Object projectIdOrPath)
public Stream<Project> getUserProjectsStream(Object userIdOrUsername, ProjectFilter filter)
public Stream<ProjectUser> getProjectUsersStream(Object projectIdOrPath, String search)
public Stream<Member> getMembersStream(Object projectIdOrPath)
public Stream<Event> getProjectEventsStream(Object projectIdOrPath)
public Stream<ProjectHook> getHooksStream(Object projectIdOrPath)
public Stream<Issue> getIssuesStream(Object projectIdOrPath)
public Stream<Snippet> getSnippetsStream(Object projectIdOrPath)
public Stream<Project> getForksStream(Object projectIdOrPath)
```

**Comment by jflefebvre06** [comment]
Thanks  a lot works fine.

The new Stream replacing pager is a very good idea !!!!!

Actually I use pager for :

- GroupApi#getSubGroups
- TagsApi#getTags
- RepositoryApi#getTree

**Comment by gmessner** [comment]
@jflefebvre06 
FYI, ```getXxxxxStream()``` methods have been added to the following API classes and are part of the 4.9.7 release:
```
GroupApi
IssuesApi
NotesApi
ProjectApi
RepositoryApi
TagsApi
UserApi
```

**Comment by gmessner** [comment]
@jflefebvre06 
The returned Stream can be used as a parallel stream, allowing the results from the API to be processed in parallel.

Keep in mind though,  that the stream is completely built when it is returned, meaning it is not reading in parallel from the REST endpoint, this cannot be done as the GitLab API itself does not allow that.

I have a unit test that needs to be checked in that tests parallel stream processing and I will add an example to the README.md showing how to do this.

**Comment by jflefebvre06** [comment]
I have tested new méthods, all works fine thank you.
