### ISSUE TITLE
IssuesApi.updateIssue requires title, an optional parameter

### ISSUE THREAD

**Issue by kyleocit** [gmessner/gitlab4j-api#285]
Two small inconsistencies I noticed with the IssuesApi class that I ran into while switching from a different library to your library:

1. IssuesApi.getIssue takes issue iid, not issue id
The comment makes this clear but the parameter name is inconsistent with other methods in the class that use an argument called issueIid.

2. IssuesApi.updateIssue requires the issue title to be provided which contradicts the method comment that specifies that the title is optional.

Neither of these things is a big deal but I figured I'd let you know.

**Comment by gmessner** [comment]
@kyleocit 
Thanks for spending your time reporting this.  Both have been corrected and the code changes pushed.  A release will be done in the next few days.

**Comment by gmessner** [comment]
@kyleocit 
4.9.10 has been released with these issues corrected.  Please verify and close when you have a chance.

**Comment by gmessner** [comment]
@kyleocit 
This has been corrected and verified, so I am closing the issue.  Please re-open if you discover otherwise.
