### ISSUE TITLE
Project entity is mostly empty

### ISSUE THREAD

**Issue by AlexanderPraegla** [gmessner/gitlab4j-api#287]
Hello,

I ran into an issue using your api wrapper: 
When I try to get a project by his id I get a mostly empty entity because the fields from the JSON reponse like e.g. "ssh_url_to_repo" could not be mapped to the field "sshUrlToRepo". Every JSON field with an underscore in the field name is not mapped.

Maybe I missed some configuration but I'm a little bit stucked at this point. 

I would be very glad about some help.

**Comment by gmessner** [comment]
How are you reading the data from the GitLab server?  You should be using the API classes provided by this library if you are not this will be the results.  For example, to get a Project instance using a project ID, the code would look like this:
```
// Create a GitLabApi instance to communicate with your GitLab server
GitLabApi gitLabApi = new GitLabApi("http://your.gitlab.server.com", "YOUR_PRIVATE_TOKEN");

// Get the Project instance for the specified ID
Project project = gitLabApi.getProjectApi().getProject(projectId);
```

The ```GitLabApi``` instance can be shared in your application, you do not need to create a new instance on each use.

`

**Comment by AlexanderPraegla** [comment]
Yes, I'm reading the data from www.gitlab.lrz.de. I am using the library exactly like the example you provided. And I'm sharing the instance through the whole application.

The reason I'm confused is, that for example in your class `Project` is no mapping from the JSON fields like "ssh_url_to_repo" which are delivered by the API to the attribute `private String sshUrlToRepo;`. 

There is only the annontation for XML mapping:
```
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Project {
```
I would have expected something like this for the JSON fields:
```
@JsonProperty("ssh_url_to_repo")
private String sshUrl;
```

**Comment by gmessner** [comment]
@AlexanderPraegla 
Using a properly configured ```ObjectMapper``` eliminates the need for per property mappings.  This library uses an ```ObjectMapper``` provided in the ```org.gitlab4j.api.utils.JacksonJson``` class.  If you take a look at the source there are two annotations at the top that configure JAX-RS to use it:
```
@Provider
@Produces(MediaType.APPLICATION_JSON)
```
My suspicion is that you have a dependency that has a different ```Provider``` configured somewhere that is being picked up instead of the one for this library.  This library is used by many projects and is thuroughly unit tested, so I can assure you that the mappings are working correctly.

**Comment by gmessner** [comment]
@AlexanderPraegla 
I am closing this issue, if you need additional assistance, please re-open.
