### ISSUE TITLE
Support API Merge Base

### ISSUE THREAD

**Issue by lethe3000** [gmessner/gitlab4j-api#288]
Get the common ancestor for 2 refs (commit SHAs, branch names or tags).

`
GET /projects/:id/repository/merge_base
`
this api is introduced in gitlab version 11.x

see https://docs.gitlab.com/ee/api/repositories.html

**Comment by gmessner** [comment]
@lethe3000 
```getMergeBase()``` has been added to the RepositoryApi and released in 4.9.12
Please verify and close when you have a chance.

**Comment by lethe3000** [comment]
thanks very much I'll verify this ASAP
