### ISSUE TITLE
Download branch off network problem

### ISSUE THREAD

**Issue by MrsZhangJie** [gmessner/gitlab4j-api#289]
"repositoryApi.getRepositoryArchive"This interface was without an error when disconnected from the network

**Comment by gmessner** [comment]
@MrsZhangJie 
I am not understanding your problem.  Have you tried using the returned InputStream, I believe when you do an error will occur?

**Comment by MrsZhangJie** [comment]
File branchesName = null;
		try {
			branchesName = repositoryApi.getRepositoryArchive(defineEntity.getGroups()+defineEntity.getName(),version,file);
			log.info("Beanches下载完毕======================>"+branchesName);
			downloadlog.setStatus(ResultCode.SUCCESS.getMsg());
		} catch (GitLabApiException e) {
			downloadlog.setStatus(ResultCode.ERROR.getMsg());
			BranchesDao.insert(downloadlog);
			response.setReturnCode(ResultCode.ERROR_DOWNLOAD.getCode());
			response.setReturnMsg(ResultCode.ERROR_DOWNLOAD.getMsg());
			e.printStackTrace();
		}finally {
			BranchesDao.insert(downloadlog);
		}

I am sorry that it may be a little difficult to communicate. I am Chinese

(branchesName = repositoryApi.getRepositoryArchive(defineEntity.getGroups()+defineEntity.getName(),version,file);)
This is the line where if the network is disconnected and no exception is thrown, the next request will come with an error

**Comment by gmessner** [comment]
@MrsZhangJie 
I cannot replicate this, if I try ```repositoryApi.getRepositoryArchive()``` when not connected I get an exception as follows:

```
org.gitlab4j.api.GitLabApiException: java.net.NoRouteToHostException: No route to host: connect
	at org.gitlab4j.api.AbstractApi.handle(AbstractApi.java:593)
	at org.gitlab4j.api.AbstractApi.getWithAccepts(AbstractApi.java:212)
	at org.gitlab4j.api.RepositoryApi.getRepositoryArchive(RepositoryApi.java:587)
	at org.gitlab4j.api.TestRepositoryApi.testRepositoryArchiveViaFile(TestRepositoryApi.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
...
```

**Comment by MrsZhangJie** [comment]
The network is disconnected halfway through the connection

**Comment by MrsZhangJie** [comment]
> @MrsZhangJie
> 我无法复制这个，如果我尝试`repositoryApi.getRepositoryArchive()`没有连接时我得到一个例外如下：
> 
> ```
> org.gitlab4j.api.GitLabApiException: java.net.NoRouteToHostException: No route to host: connect
> 	at org.gitlab4j.api.AbstractApi.handle(AbstractApi.java:593)
> 	at org.gitlab4j.api.AbstractApi.getWithAccepts(AbstractApi.java:212)
> 	at org.gitlab4j.api.RepositoryApi.getRepositoryArchive(RepositoryApi.java:587)
> 	at org.gitlab4j.api.TestRepositoryApi.testRepositoryArchiveViaFile(TestRepositoryApi.java:172)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> ...
> ```

The network is disconnected halfway through the connection

**Comment by MrsZhangJie** [comment]
> > @MrsZhangJie 
> > 我无法复制这个，我如果尝试`repositoryApi.getRepositoryArchive()`没有连接时我得到一个例外如下：
> > ```
> > org.gitlab4j.api.GitLabApiException: java.net.NoRouteToHostException: No route to host: connect
> > 	at org.gitlab4j.api.AbstractApi.handle(AbstractApi.java:593)
> > 	at org.gitlab4j.api.AbstractApi.getWithAccepts(AbstractApi.java:212)
> > 	at org.gitlab4j.api.RepositoryApi.getRepositoryArchive(RepositoryApi.java:587)
> > 	at org.gitlab4j.api.TestRepositoryApi.testRepositoryArchiveViaFile(TestRepositoryApi.java:172)
> > 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> > 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> > 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> > 	at java.lang.reflect.Method.invoke(Method.java:498)
> > 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> > 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> > 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> > 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> > 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
> > 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> > 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> > ...
> > ```
> 
> 网络在连接中途断开连接
The network is disconnected halfway through the connection
