### ISSUE TITLE
Wikis attachements

### ISSUE THREAD

**Issue by taomWTP** [gmessner/gitlab4j-api#290]
Hello,

Seems like wikis attachments are not supported. Could you please add this feature?
https://docs.gitlab.com/ee/api/wikis.html#upload-an-attachment-to-the-wiki-repository

**Comment by gmessner** [comment]
@taomWTP 
We will add support for this to the release being done on 1/21/2019

**Comment by taomWTP** [comment]
Great, thank you.

And the second issue which i found is that list of sub APIs in main project description doesn't contain WikisApi.
I was looking for api which supports wikis and almost missed that your implementation supports it.

**Comment by gmessner** [comment]
@taomWTP 
GitLab4J-API version 4.9.14 has been released with support for Wiki attachment upload has been added as well as adding the WikisApi to README.md.  Please verify and close when you have time.

**Comment by taomWTP** [comment]
Works fine, thank you for fast response.
