### ISSUE TITLE
Create discussions

### ISSUE THREAD

**Issue by tomasbjerre** [gmessner/gitlab4j-api#291]
I was looking for a way to create new discussions. And specifically on merge requests. https://docs.gitlab.com/ee/api/discussions.html#create-new-merge-request-discussion

This is not currently supported right?

**Comment by gmessner** [comment]
@tomasbjerre 
Will will include discussion management methods to the DiscussionsApi in the next release scheduled for 1/28/2019

**Comment by gmessner** [comment]
@tomasbjerre 
My apologies for taking so long to get this released.  The DiscussionsApi now has the ability to create and resolve merge request discussions and delete notes from a merge request discussion.

4.9.15 is now available, please verify and close this issue when you have time.

**Comment by tomasbjerre** [comment]
Thanks!!
