### ISSUE TITLE
Name should not be required to update a project.

### ISSUE THREAD

**Issue by Nick-Anderssohn** [gmessner/gitlab4j-api#292]
An exception is thrown with the message `Project name cannot be null or empty` when you pass a `Project` that has a null name to `ProjectApi`'s `updateProject`  method. Name is not required by GitLab's API: https://docs.gitlab.com/ee/api/projects.html#edit-project The exception was thrown at line 1036 in ProjectApi.java, but it looks like other places in the code may need to be updated too.

**Comment by gmessner** [comment]
@Nick-Anderssohn 
This has been fixed and will be released in 4.9.15 later today.  The code change has already been committed if you'd like to see the fix.

**Comment by gmessner** [comment]
@Nick-Anderssohn 
This has finally been released, please verify and close this issue when you have time.

**Comment by gmessner** [comment]
@Nick-Anderssohn 
This issue has been verified fixed, so am closing the issue.  Feel free to re-open if you find any issues with the fix.

**Comment by Nick-Anderssohn** [comment]
Sorry I didn't respond quicker, I was out of the country. Thanks for fixing this so fast!
