### ISSUE TITLE
Improvement: Add optional parameters to GroupsApi.getGroups

### ISSUE THREAD

**Issue by Nick-Anderssohn** [gmessner/gitlab4j-api#302]
Listed [here](https://docs.gitlab.com/ee/api/groups.html#list-groups) are a bunch of optional parameters that `GET /groups` can take. The one that I specifically needed to be able to set was `min_access_level`, but I imagine they should just all be added in one feature.

**Comment by gmessner** [comment]
@Nick-Anderssohn 
There are now methods for fetching the groups using ```GroupFilter```.  This has been released in 4.9.17. Please verify and close when you have a chance.

**Comment by Nick-Anderssohn** [comment]
@gmessner Thanks for the quick response. While verifying, I only found 1 bug. On [line 139 in GroupFilter.java](https://github.com/gmessner/gitlab4j-api/blob/0ae30f9e2a7ef1e843b815d99bb133e16d9ee46a/src/main/java/org/gitlab4j/api/models/GroupFilter.java#L139), there is a space in the `"min_access_level "` string at the tail end which causes it to be url encoded incorrectly (it ends up adding a `+` where that space is). I can create a pull request if you want, but I figure since it's just a one character change, you probably can just do it. Thanks again for maintaining this awesome library!

**Comment by gmessner** [comment]
@Nick-Anderssohn 
Thanks for verifying.  The fix has been made and pushed, will be included in the next release, which should be in the next day or two.

**Comment by gmessner** [comment]
@Nick-Anderssohn 
This has been fixed and is available in release 4.9.18, please verify and close when you have a chance.  My apologies for the delay,

**Comment by Nick-Anderssohn** [comment]
@gmessner 
No worries, thanks for the fix! Will check it out within the next couple of days.

**Comment by Nick-Anderssohn** [comment]
LGTM
