### ISSUE TITLE
A bug in projects API while getting all projects using getProjects()

### ISSUE THREAD

**Issue by Iruora** [gmessner/gitlab4j-api#305]
_________________________________
Hello, here in the [documentation](https://docs.gitlab.com/ee/api/#other-pagination-headers) you will find this caution which is not handled in the Pager class.
This exception appears when invoking getProjects() method from the ProjectApi : 
_________________________________
**org.gitlab4j.api.GitLabApiException: Missing 'X-Total-Pages' header from server**
_________________________________
![issue](https://user-images.githubusercontent.com/22733738/52917050-27518980-32e7-11e9-8db9-eb2106161497.PNG)
_________________________________
**Caution:** For performance reasons since GitLab 11.8 and behind the api_kaminari_count_with_limit feature flag, if the number of resources is more than 10,000, the X-Total and X-Total-Pages headers as well as the rel="last" Link are not present in the response headers.
_________________________________
Best regards. 👍

**Comment by gmessner** [comment]
@Iruora 
This has been fixed and is available in release 4.9.18.
I have no way to test the fix, so please verify and close when you have a chance.

**Comment by Iruora** [comment]
Great I've tested the method and it throws no more any exception and ends with grabbing query result successfully.
