### ISSUE TITLE
RepositiryApi compare(...) method problem, its not providing filepath and name details along with diff content.

### ISSUE THREAD

**Issue by muralikrissna** [gmessner/gitlab4j-api#307]
Our private GitLab is upgraded to v11.6.5, after the upgrade we couldn't find the file details along with diff object, I have tried the latest version 4.9.16 (with v4) as well.

Here is the Api we are using to get the file diffs in between the commits.

```
CompareResults results= gitLabApi.getRepositoryApi().compare(projectId, startCommitId, 
                                endCommitID);
List<Diff> diffs = results.getDiffs();

```

We could see diff content for each and every Diff, but it doesn't contains filepath and name.

Please find the diff content we are expecting, before 11.x upgrade RepositoryApi used to return diff content with file details(first 2 lines) as below.

```
--- a/myproj/pom.xml
+++ b/myproj/pom.xml
@@ -53,7 +53,7 @@
       <dependency>
           <groupId>org.gitlab4j</groupId>
           <artifactId>gitlab4j-api</artifactId>
-          <version>4.9.14</version>
+          <version>4.9.16</version>
```

After upgrade RepositoryApi is not returning file details.

```
@@ -53,7 +53,7 @@
       <dependency>
           <groupId>org.gitlab4j</groupId>
           <artifactId>gitlab4j-api</artifactId>
-          <version>4.9.14</version>
+          <version>4.9.16</version>
```

As we won't have filepath and name details as part of diff now. We couldn't understood, which file the diff belongs to.

**Comment by gmessner** [comment]
@muralikrissna 
This library has no control over the content of the diff element, that is provided in the response from the GitLab server.  It appears you have discovered a bug with GitLab 11

Take a look at the last comment in the following GitLab issue:
https://gitlab.com/gitlab-org/gitlab-ce/issues/50014

It indicates that the diffs are bing cut-off because they are too large.

**Comment by muralikrissna** [comment]
@gmessner 
https://gitlab.com/gitlab-org/gitlab-ce/issues/57702 issue is not identical to my issue.

In my case I could see the content of each and every diff, its not empty diff.

Today only I noticed gitlab api is ***not** populating the file paths as part of diff content. Instead they are populating file paths as "old_path" and "new_path" json elements. 

I accessed gitlab rest api using below url.

`/api/v4/projects/<project-id>/repository/commits/<SHA>/diff`.

But RepositoryAPI is not populating oldPath and newPath of Diff object, they are **null**. It will be great if RepositoryAPI is populating the paths, then only we can relate diffs and files.

**Comment by gmessner** [comment]
@muralikrissna 
The endpoint you referenced (/api/v4/projects/<project-id>/repository/commits/<SHA>/diff) is in the ```CommitsApi``` not the ```RepositoryApi```.  Try using the following in the ```CommitsApi```:
```
public List<Diff> getDiff(Object projectIdOrPath, String sha)
```

`

**Comment by muralikrissna** [comment]
@gmessner 
I have tried **CommitsApi** as below, I am seeing the same issue.  CommitApi is also not populating oldPath and newPath of Diff object. 

`gitLabApi.getCommitsApi().getDiff(projectId, commitId)`

As stated earlier I could see gitlab-api json response contains `old_path` and `new_path` with data.

I have tried below gitlab-api rest url as well to get the diffs in between commits, which is being wrapped by RepositoryApi. I could see  `old_path` and `new_path` data as part of json response.

`/api/v4/projects/<project-d>/repository/compare?from=<SHA>&to=<SHA>`

Thanks for your prompt response, is there any way to fix this issue.

**Comment by gmessner** [comment]
@muralikrissna 
Could you provide the actual JSON response that includes the old_path and new_path data?

**Comment by muralikrissna** [comment]
@gmessner 
Please find the json response,  as I am not allowed to share actual data, I have masked the data.


For the URL `/api/v4/projects/<project-id>/repository/commits/<SHA>/diff`, please find the json response below

**Json Response**
```
[   
        {    "old_path":"core/src/main/java/codereview/service/data/XxxDAO.java",
	     "new_path":"core/src/main/java/codereview/service/data/XxxDAO.java",
	     "a_mode":"100644",
	     "b_mode":"100644",
	     "new_file":false,
	     "renamed_file":false,
	     "deleted_file":false,
	     "diff":"@@ -114,5 +114,13 @@ I could see dif content here \n"
	},
	
	{   "old_path":"core/src/main/java/codereview/service/data/XxxService.java",
	    "new_path":"core/src/main/java/codereview/service/data/XxxService.java",
	    "a_mode":"100644",
	    "b_mode":"100644",
	    "new_file":false,
	    "renamed_file":false,
	    "deleted_file":false,
	    "diff":"@@ -5,6 +5,7 @@ I could see dif content here\n"
	}
]
```

For the URL `/api/v4/projects/<project-d>/repository/compare?from=<SHA>&to=<SHA>` please find response as attachment. [response.txt](https://github.com/gmessner/gitlab4j-api/files/2899799/response.txt)

**Comment by muralikrissna** [comment]
@gmessner 
Hi, Do we have any update on this issue.

Thank You.

**Comment by gmessner** [comment]
@muralikrissna 
I am unable to replicate the issue.  Tested with both GitLab 11.6.0 and 11.6.5.  

Many times when data is not being populated in the GitLab4J models the problem is how the library is being used.  If you are trying to use the model classes outside of GitLab4J you must use the ```ObjectMapper``` provided by ```org.gitrlab4j.api.utils.JacksonJson.getObjectMapper()``` to unmarshal the data.

If you are properly using the library, then there is likely a problem outside of the library.

**Comment by muralikrissna** [comment]
@gmessner 
Thank You for you time. I have wrote a standalone program by having gitlab4j-api library only in workspace, its working as expected I could see all the properties are populated.

I have Jersey and Jackson dependencies in my application workspace, may be there is a conflict.

Thank You for your support.

**Comment by gmessner** [comment]
@muralikrissna 
Jackson and Jersey have changed how some of the name conversion defaults over the last few years.  The problem may be just a version issue,   This library uses the following:

Jackson: 2.9.8 (latest version)
Jersey: 2.27 (latest is 2.28 released in Jan 2019)

If you use the same version it may correct the issue.
