### ISSUE TITLE
Add Delete merged branches api

### ISSUE THREAD

**Issue by philippe-granet** [gmessner/gitlab4j-api#312]
https://docs.gitlab.com/ce/api/branches.html#delete-merged-branches
Will delete all branches that are merged into the project’s default branch.

DELETE /projects/:id/repository/merged_branches

curl --request DELETE --header "PRIVATE-TOKEN: <your_access_token>" https://gitlab.example.com/api/v4/projects/5/repository/merged_branches

**Comment by gmessner** [comment]
@philippe-granet 
This has been added and is available in release 4.9.18, please verify and close when you have a chance.

**Comment by gmessner** [comment]
@philippe-granet 
I'm closing this since the functionality has been added and released.  Feel free to re-open if you find any issues with the implementation.
