### ISSUE TITLE
Improvement: Add method to delete pipeline

### ISSUE THREAD

**Issue by SamerAdra** [gmessner/gitlab4j-api#313]
Added in GitLab 11.6 is a method to delete a pipeline.
https://docs.gitlab.com/ee/api/pipelines.html#delete-a-pipeline

**Comment by gmessner** [comment]
@SamerAdra 
This has been added and is available in release 4.9.18, please verify and close when you have a chance.

**Comment by SamerAdra** [comment]
Works like a charm. Tested against GitLab 11.8.0-ee. Thank you @gmessner.
