### ISSUE TITLE
Disable runner not correctly implemented

### ISSUE THREAD

**Issue by olivierpaquet** [gmessner/gitlab4j-api#315]
The disable runner operation is executing a wrong request:

Executing request DELETE /api/v4/projects/20218/runners?runner_id=2632 HTTP/1.1

But as per spec it should be DELETE /projects/:id/runners/:runner_id [https://docs.gitlab.com/ee/api/runners.html#disable-a-runner-from-project].

**Comment by gmessner** [comment]
@olivierpaquet 
This has been fixed and is available in release 4.9.18, please verify and close when you have a chance.

**Comment by gmessner** [comment]
@olivierpaquet 
I'm closing this since it has been fixed.  Feel free to re-open if you find any issues with the fix.
