### ISSUE TITLE
Adding Issue Boards Api

### ISSUE THREAD

**Issue by Ningpuh** [gmessner/gitlab4j-api#316]
Can u add Issue Boards API?
https://docs.gitlab.com/ee/api/boards.html

**Comment by gmessner** [comment]
@Ningpuh 
Support for the Issues Board API will be added in the next week's release, look for it by 3/29/2019.

**Comment by Ningpuh** [comment]
Hi,
seems like Issues Board API didn't make it in the latest release. Is it delayed or canceled ?

**Comment by gmessner** [comment]
@Ningpuh 
Neither, because it was a new API, it took a bit longer to implement.  The BoardsApi is included in the latest release (4.9.21).  Please verify and close when you have a chance.

**Comment by Ningpuh** [comment]
First off all: thanks for the good work. But I still have an issue with the Boards API, maybe i'm doing something wrong. I've created a new project and a new label, but when i want to create a new board list it demands a board id.  I thought i get all the boards of the project and take the first one (because i'm on the community edition, where you can only have one board per project) but it returns an empty list. If I visit the Project Board Side on GitLab and retry the request getBoards it works. But if I want to create 80 new projects, I don't want to visit all 80 Project Boards before I can create lists. Am I doing something wrong ?

**Comment by gmessner** [comment]
@Ningpuh 
This is an issue with GitLab CE, not this library, the CE version does not support creating a board via the API, that is only supported in GitLab EE.  This causes you to go thru the UI and visit the board to have it automatically created.

I would suggest you file an issue with GitLab, asking that support be added to GitLab CE for creating the single issue board via the API.

**Comment by Ningpuh** [comment]
Ok, thx for the quick response. You helped me a lot.
