### ISSUE TITLE
Package API

### ISSUE THREAD

**Issue by jflefebvre06** [gmessner/gitlab4j-api#317]
Hello Greg
Could you please add package API : 
https://docs.gitlab.com/ee/api/packages.html

**Comment by gmessner** [comment]
@jflefebvre06 
The PackagesApi has been added, a release will be done in the next few days.

**Comment by jflefebvre06** [comment]
@gmessner Thanks greg

**Comment by gmessner** [comment]
@jflefebvre06 
Release 4.9.19 with this functionality has been released. Please verify and close when you have a chance.

**Comment by gmessner** [comment]
@jflefebvre06 
Since the enhancement has been released I am closing this issue, feel free to open it back up if you find any problems with the implementation.

**Comment by jflefebvre06** [comment]
Hello @gmessner 
Sorry for the delay, I was waiting my company install gitlab 11.8. I have checked dotay and all works fine.
Thanks a lot
JF
