### ISSUE TITLE
Pipeline schedules Api

### ISSUE THREAD

**Issue by lpiet** [gmessner/gitlab4j-api#318]
Hi Greg,

I couldn't find any calls for the pipeline-schedule api (https://gitlab.com/help/api/pipeline_schedules.md) Are these within the scope of the project?

Thanks,

Louis

**Comment by gmessner** [comment]
@lpiet 
I'll leave this open and use it to let you know when the release of your PR has been completed.

**Comment by gmessner** [comment]
@lpiet 
Release 4.9.19 with your PR has been released. Please verify and close when you have a chance.

FYI, ```modifyPiplelneSchedule()``` was rename ```updatePipelineSchedule()``` to follow this library's nbaming conventions.

**Comment by lpiet** [comment]
thanks, when i get back to the office i'll verify and close, gone for a few more days

**Comment by gmessner** [comment]
@lpiet 
Since the enhancement has been released I am closing this issue, feel free to open it back up if you find any problems with the implementation.
