### ISSUE TITLE
JobsApi

### ISSUE THREAD

**Issue by spingaroliver** [gmessner/gitlab4j-api#32]
[JobsApi](https://docs.gitlab.com/ee/api/jobs.html) is not implemented yet. Do you plan implement it? I need it for artifact download.

**Comment by gmessner** [comment]
@spingaroliver 
I will try and get it implemented over the weekend.  If I sent you the definition for the JobsApi class could you provide feedback before I implement?

**Comment by spingaroliver** [comment]
Next week I will be on holiday, but after it I check it and provide feedback.

**Comment by neillau24** [comment]
I can not download the api version 4.3.0 from mvnrepository ,please upload the artifact ,thank u ! : )

**Comment by gmessner** [comment]
@spingaroliver 
The Job API was added by Pull Request #45 

I will be putting a release together today.

**Comment by gmessner** [comment]
@spingaroliver 
I have release GitLab4J-API 4.4.0. with support for the Job API.
