### ISSUE TITLE
could WebHook entity add toString ?

### ISSUE THREAD

**Issue by magaofei** [gmessner/gitlab4j-api#320]
I want to print with webhook entity , for instance, `PushEvent` but not implement toString()

**Comment by gmessner** [comment]
@magaofei 
toString() has been added to all the webhook and systemhook events classes.  This will be included in this weeks release which should be in the next 2 days or so.

**Comment by gmessner** [comment]
@magaofei 
Release 4.9.19 with this functionality has been released. Please verify and close when you have a chance.

**Comment by gmessner** [comment]
@magaofei 
Since the enhancement has been released I am closing this issue, feel free to open it back up if you find any problems with the implementation.
