### ISSUE TITLE
Missing straight parameter for repositories' compare method

### ISSUE THREAD

**Issue by Fractaliste** [gmessner/gitlab4j-api#322]
[The Repositories' compare method](https://docs.gitlab.com/ee/api/repositories.html#compare-branches-tags-or-commits) expose a query param named `straight` which seems not to be implented yet :

https://github.com/gmessner/gitlab4j-api/blob/537849206e38b20c08ce39a845733f68a1d21dfa/src/main/java/org/gitlab4j/api/RepositoryApi.java#L672-L687

**Comment by gmessner** [comment]
@Fractaliste 
This will be added in the next release which will be in the next couple days.

**Comment by gmessner** [comment]
@Fractaliste 
Support has been added for the straight param and is available in release 4.9.20.  Please verify and close when you have a chance.

**Comment by gmessner** [comment]
@Fractaliste 
Since this issue has been addressed in the latest release I am closing this issue, if you find any problems with the implementation, please feel free to re-open this issue.
