### ISSUE TITLE
Add labels support to IssueEvent returned via Webhook

### ISSUE THREAD

**Issue by jkomyno** [gmessner/gitlab4j-api#325]
Hi, thanks for this library.
I've noticed that even if the [Label](https://github.com/gmessner/gitlab4j-api/blob/master/src/main/java/org/gitlab4j/api/models/Label.java) model is defined, it doesn't seem to be possible to retrieve the list of labels from an [IssueEvent](https://github.com/gmessner/gitlab4j-api/blob/master/src/main/java/org/gitlab4j/api/webhook/IssueEvent.java) retrieved from GitLab's webhook API. Could it be added? Would you accept a PR with this feature?

**Comment by gmessner** [comment]
@jkomyno 
The IssueEvent has had a few fields added recently with labels being one of them.  We will add the missing fields to the event and include in the next release, which should be in the next few days.

**Comment by jkomyno** [comment]
Thank you for the prompt response, I'm looking forward for the next release.

**Comment by gmessner** [comment]
@jkomyno 
Support has been added for labels in the issue-event and is available in release 4.9.20.  Please verify and close when you have a chance.

**Comment by gmessner** [comment]
@jkomyno 
Since this feature is available in the latest release I am closing this issue, if you find any problems with the implementation, please feel free to re-open this issue.

**Comment by gmessner** [comment]
If there is no label property in the event JSON it will return null, I cannot say whether that will ever be the case or not.
