### ISSUE TITLE
Support variables in PipelineSchedule

### ISSUE THREAD

**Issue by dawi** [gmessner/gitlab4j-api#326]
It would be nice to support PipelineSchedule Variables.

https://docs.gitlab.com/ce/api/pipeline_schedules.html

Keep up the great work. This is such a useful project!!! :)

**Comment by gmessner** [comment]
@dawi 
Support has been added for pipeline schedule variables and is available in release 4.9.20.  Please verify and close when you have a chance.

**Comment by gmessner** [comment]
@dawi 
Since this feature is available in the latest release I am closing this issue, if you find any problems with the implementation, please feel free to re-open this issue.
