### ISSUE TITLE
commitsApi.getCommit(projectId, branchName) fails with 404 if slash in branch name

### ISSUE THREAD

**Issue by SamerAdra** [gmessner/gitlab4j-api#328]
When I call, e.g., commitsApi.getCommit(1672, "feature/my-feature-name"), it throws a GitLabApiException with "404 Not Found."

When I URL-encode the branch name, it succeeds.

Using 4.9.18

**Comment by gmessner** [comment]
@SamerAdra 
This has been fixed and released in 4.9.22.  Please verify and close this issue when you have a chance.

**Comment by SamerAdra** [comment]
Verified fixed. Thanks!
