### ISSUE TITLE
getCommits(project_id) cannot get all commits in a project

### ISSUE THREAD

**Issue by neillau24** [gmessner/gitlab4j-api#33]
getCommits(project_id) cannot get all commits in a project

only get max 20 commits in a project

**Comment by gmessner** [comment]
Release 4.2.5 has updated the CommitsApi.getBranches(int projectId) to return the DEFAULT_PER_PAGE of 9999 commits.  Over the next week, the Pager functionality will be added that will provide the ability to fetch the commits in a paged way.
