### ISSUE TITLE
Support Group-level and Project-level variables.

### ISSUE THREAD

**Issue by Lasering** [gmessner/gitlab4j-api#330]
It would be nice to support Group-level and Project-level variables:

https://docs.gitlab.com/ee/api/group_level_variables.html
https://docs.gitlab.com/ee/api/project_level_variables.html

Keep up the excelent work.

**Comment by gmessner** [comment]
@Lasering 
Support for both project and group variables has been added and released in 4.9.22.  Please verify and close this issue when you have a chance.

**Comment by Lasering** [comment]
That was the fastest I've ever seen someone add a new feature in a open source project. Kudos to you sir.
