### ISSUE TITLE
Does the system hook api support the merge request?

### ISSUE THREAD

**Issue by magaofei** [gmessner/gitlab4j-api#332]
![image](https://user-images.githubusercontent.com/3363787/56196134-d8b33800-6068-11e9-991a-d07e1b92436c.png)

I need this feature, but I didn't find it in `org.gitlab4j.api.systemhooks.SystemHookListener`

log
```
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class org.gitlab4j.api.systemhooks.SystemHookEvent]: missing type id property 'event_name'
 at [Source: (String)"{"object_kind":"merge_request","event_type":"merge_request",
```

**Comment by gmessner** [comment]
@magaofei 
Support for the merge_request system hook has been added and release 4.10.0 has been published.  Please verify and close this issue when you have time.

**Comment by magaofei** [comment]
```
2019-04-17 15:54:15.364  WARN 172.16.16.239 --- [nio-8123-exec-7] c.t.e.s.s.i.GitLabServiceImpl            : get post data error e =
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class org.gitlab4j.api.systemhooks.SystemHookEvent]: missing type id property 'event_name'
 at [Source: (String)"{"object_kind":"merge_request","event_type":"merge_request","user"
```

**Comment by magaofei** [comment]
@gmessner 
```
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class org.gitlab4j.api.systemhooks.SystemHookEvent]: missing type id property 'event_name'
 at [Source: (String)"{"object_kind":"merge_request","event_type":"merge_request","user"
```

**Comment by gmessner** [comment]
@magaofei 
Based on the JSON you have provided, It appears that the documentation at:
https://docs.gitlab.com/ee/system_hooks/system_hooks.html#merge-request-events
is not correct.

Notice that the documentation excludes the ```"event_name"``` property.  I actually had to add code to make it work because ```"event_name"``` was missing. From the JSON you provided it appears that ````"event_name"``` is actually present, which is what is causing this problem.   This is an easy fix, which I will release later today.

**Comment by gmessner** [comment]
@magaofei 
4.10.1 has just been released, please re-verify and close if it is now working.

**Comment by gmessner** [comment]
@magaofei 
4.10.2 has been that improved things the handling of MergerRequestSystemHookEvent, and added a test for SystemHookManager.handleEvent(), please verify this version.

**Comment by magaofei** [comment]
@gmessner 
```
2019-04-18 15:38:28.809  WARN 172.16.16.240 --- [nio-8123-exec-9] c.t.e.s.s.i.GitLabServiceImpl            : get post data error e =
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class org.gitlab4j.api.systemhooks.SystemHookEvent]: missing type id property 'event_name'
 at [Source: (String)"{"object_kind":"merge_request","event_type":"merge_request","user"
```

**Comment by magaofei** [comment]
It works fine
