### ISSUE TITLE
commit contain file information

### ISSUE THREAD

**Issue by Sun-k** [gmessner/gitlab4j-api#337]

**Comment by Sun-k** [comment]
List<Commit> commitsAll = gitLabApi.getCommitsApi().getCommits(123)
how could i found commit fileName or filePath by this "commit" information

**Comment by gmessner** [comment]
@Sun-k 
Commits can have many files associated with them, and sometimes it's a rename, a delete, etc.  So in order to get this information you need to get the diffs associated with the commit as follows:
```
List<Commit> commitsAll = gitLabApi.getCommitsApi().getCommits(123);
for (Commit commit : commitsAll) {
    List<Diff> diffs = gitLabApi.getCommitsApi().getDiffs(123, commit.getId());
    // Each diff has information related to the associated file
}
```

**Comment by Sun-k** [comment]
oh thank you ! 
I found it finally that is : gitLabApi.getCommitsApi().getDiff(123, commit.getId());
