### ISSUE TITLE
please add branch api

### ISSUE THREAD

**Issue by neillau24** [gmessner/gitlab4j-api#36]
please add branch api

**Comment by gmessner** [comment]
@neillau24 
The Branch related API calls are found in the RepositoryApi, are these not sufficient?

**Comment by neillau24** [comment]
@gmessner 
I find the branchapi in RepositoryApi , but I can not get the branch create time in branchapi , also as the MergeRequestAPI ( Ican not find the MergeRequest create time  and the merged or closed time)

**Comment by neillau24** [comment]
This is restful api result in gitlab ce 9.2.5 , it has "created_at" and "updated_at" properties , but I can not get this two properties  by the RepositoryApi 


[{"id":47,"iid":1,"project_id":17,"title":"S1Merge","description":"","state":"merged",**"created_at":"2017-06-02T17:59:32.274+08:00","updated_at":"2017-06-02T18:08:41.932+08:00"**,"target_branch":"master","source_branch":"S1","upvotes":0,"downvotes":0,"author":{"name":"施昊华-测试部","username":"shihaohua","id":5,"state":"active","avatar_url":"https://secure.gravatar.com/avatar/1ed2ec7e8cf72a275ec622c2f7cd71cc?s=80\u0026d=identicon","web_url":"https://10.10.2.122:8443/shihaohua"},"assignee":null,"source_project_id":17,"target_project_id":17,"labels":[],"work_in_progress":false,"milestone":null,"merge_when_pipeline_succeeds":false,"merge_status":"can_be_merged","sha":"81d029620af10bbd08ee4be56fd10876e65ad4f8","merge_commit_sha":"0e901d8dcc55cf63313a1df54086a4cf04a0c0ea","user_notes_count":1,"should_remove_source_branch":null,"force_remove_source_branch":null,"web_url":"https://10.10.2.122:8443/cm/gitlab-audit/merge_requests/1"}]

**Comment by DieZZzz** [comment]
@gmessner I think, @neillau24 is talking about **created_at** and **updated_at** properties that are missing from MergeRequest.
It will be really nice if you could add them :)

**Comment by neillau24** [comment]
@DieZZzz that is what I think，I can not get the mergerequest or the branch's create time or update time   properties.

**Comment by gmessner** [comment]
According to the Branch and Merge Request API docs, neither have the created_at or updated_at fields, which is why I have not implemented them.  See: 
https://docs.gitlab.com/ce/api/branches.html#get-single-repository-branch
https://docs.gitlab.com/ce/api/merge_requests.html#get-single-mr

**Comment by gmessner** [comment]
@DieZZzz
@neillau24
I decided it wouldn't hurt to include the created_at and updated_at fields in the MergeRequest class, which I have done.

GitLab4J-API 4.3.2 has just been released with this change.

**Comment by neillau24** [comment]
thank you very much!!!
@gmessner
