### ISSUE TITLE
no support SSH key

### ISSUE THREAD

**Issue by 44010083** [gmessner/gitlab4j-api#37]
can we support SSH-key?
https://gitlab.com/help/api/users.md,POST /users/:id/keys

**Comment by gmessner** [comment]
To be clear, you are looking to have the various SSH key management API calls implemented for the Users API?

**Comment by 44010083** [comment]
yes,i am looking for SSH key management API

**Comment by gmessner** [comment]
I'll get this functionality scheduled to be completed in the next week or so.

**Comment by gmessner** [comment]
SSH key support has been added to UserApi.  The code is checked in if you want to take a look, it will be released tomorrow after unit tests are completed.

**Comment by 44010083** [comment]
wonderful
