### ISSUE TITLE
Compare branches, tags, or commits implementation? and CommitsApi.getDiff() problem!

### ISSUE THREAD

**Issue by OchirnyamB** [gmessner/gitlab4j-api#38]
I was wondering if the API has implemented the 

GET /projects/:id/repository/compare?from=master&to=feature from GitLab Repository API

under comparing branches, tags, or commits page at: https://docs.gitlab.com/ce/api/repositories.html

I am trying to the get blame file between a range of commits and I started of by getting a single diff of a specific commit,  but run into an exception Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of org.gitlab4j.api.models.Diff out of START_ARRAY token
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@1b2c4791; line: 1, column: 1]

The call that I'm making is 

Diff diff = gitLabApi.getCommitsApi().getDiff(projectId,commit.getId());

and I made sure the projectId and the hash was correct.

Would like a response as soon as possible, thank you!

**Comment by gmessner** [comment]
The getDiff() method has been fixed and the compare() method has been added. Unit tests have been added to test this functionality.

**Comment by OchirnyamB** [comment]
Thank you for your quick response and fix for the issue!
