### ISSUE TITLE
RepositoryFileApi.createFile does not create the file

### ISSUE THREAD

**Issue by cdchudasama** [gmessner/gitlab4j-api#40]
Hi,

I have recently started to use this API and have run into an issue when trying to create a file. I do the following:
1. Create a RepositoryFile object with a URL encoded file path and content
2. Call the RepositoryFileApi's createFile method passing the repository file object, the project id, the branch name, and the commit message. 

But I get a "Not Found!" error back and the file is not created.

Upon further investigation, I found that the url used for the create file POST does not contain the file path and so the POST request fails. I added the file path to the URL in the debugger and the file was created.

1. Am I missing something in the way I am using the createFile method?
2. If this is a bug what would the ETA of getting a fix?

I am using the latest version from maven: 4.3.4.

Thanks,
Chetan

**Comment by gmessner** [comment]
GitLab4J-API Release 4.3.6 has been released with fixes to the RepositoryFileApi.
