### ISSUE TITLE
DEFAULT_PER_PAGE is not work

### ISSUE THREAD

**Issue by ccl0326** [gmessner/gitlab4j-api#41]
In gitlab api the max per page has a limit value, so if the item size larger than the value, the api with DEFAULT_PER_PAGE can not fetch the all items except fetch items with many times.

**Comment by gmessner** [comment]
You canuse the appropriate method that returns a Pager<> instance and use it to pull down the entire list.  For projects it would look something like this:

```java
// Get a Pager instance that will page through the projects with 20 projects per page
Pager<Project> projectPager = gitlabApi.getProjectsApi().getProjectsPager(20);
List<Project> allProjects = new ArrayList<>(projectPager.getTotalItems());

// Iterate through the pages and append each page of projects to the list
while (projectsPager.hasNext())
    allProjects.addAll(projectsPager.next());
```

**Comment by gmessner** [comment]
@ccl0326 
Did the above answer your question?

**Comment by ccl0326** [comment]
@gmessner yep, it can answer my question.
