### ISSUE TITLE
Trigger a pipeliine

### ISSUE THREAD

**Issue by lumeche** [gmessner/gitlab4j-api#44]
Does the library has support to trigger a pipeline? It would send a request like 
`curl -X POST -F token=<pipeline> -F ref=<reference> https://git.labs.yourserver.com/api/v4/projects/<yourProject>/trigger/pipeline`

**Comment by gmessner** [comment]
Unfortunately, this call is part of  GitLab CI, not GitLab API, so it is not part of this library.

**Comment by gmessner** [comment]
@lumeche 
First off I'd like to apologize for not putting more research into this when you first posted the issue.  

I know it has been nearly 2 years, but I thought I'd let you know that full support for pipeline triggers as well as triggering a pipeline has been recently added to this library.
