### ISSUE TITLE
get all commits

### ISSUE THREAD

**Issue by 44010083** [gmessner/gitlab4j-api#47]
we can get all commits from network:
http://{host}/{space}/{repos}/network/master?format=json

can we have an api get all commits by this way?

**Comment by gmessner** [comment]
@44010083 
This doesn't appear to be part of the GitLab API, if it is can you point me to the API docs?

**Comment by gmessner** [comment]
@44010083 
Using the API, you can fetch all commits for a project by using a Pager as follows:

```java
// Create a Pager instance that will be used to build a list containing all the commits for project ID 1234
Pager<Commit> commitPager = gitlabApi.getCommitsApi().getCommits(1234, 20);
List<Commit> allCommits = new ArrayList<>(commitPager.getTotalItems());

// Iterate through the pages and append each page of commits to the list
while (commitPager.hasNext())
    allCommits.addAll(commitPager.next());
```
