### ISSUE TITLE
How to ignore certificate errors?

### ISSUE THREAD

**Issue by tomasbjerre** [gmessner/gitlab4j-api#51]
I found this method:
https://github.com/gmessner/gitlab4j-api/blob/master/src/main/java/org/gitlab4j/api/GitLabApiClient.java#L159

How do I set this attribute when I have a GitLabApi?

I see a getter that could have been used to get the client and then use the setter in GitLabApiClient. But it is package private:
https://github.com/gmessner/gitlab4j-api/blob/master/src/main/java/org/gitlab4j/api/GitLabApi.java#L242

**Comment by gmessner** [comment]
I have been debating on whether to expose this.  Since you need this functionality I will expose it via the GitLabApi in the next release.

**Comment by gmessner** [comment]
GitLab4J-API version 4.4.2 has been released with the following method available in the GitLabApi class:

```java
public void setIgnoreCerificateErrors(boolean ignoreCertificateErrors)
```
