### ISSUE TITLE
RepositoryFileApi.getRawFile throws GitLabApiException (404 File Not Found) when filepath argument contains '.'

### ISSUE THREAD

**Issue by nachawati** [gmessner/gitlab4j-api#53]
GitLab API apparently requires '.' to be escaped when getting raw files, but AbstractApi.urlEncode does not escape '.'

**Comment by gmessner** [comment]
Looks like this is a bug with GitLab itself (see [API to "Get raw file from repository" fails for files with dots](https://github.com/gmessner/gitlab4j-api/issues/53)).  That being said, it will not break the REST API calls if ".", "-", and "_" are encoded, so I will modify urlEncode() to escape these characters.  Should be released today.

**Comment by gmessner** [comment]
This has been fixed and is available in release 4.4.3.
