### ISSUE TITLE
Getting currently authenticated user via private token

### ISSUE THREAD

**Issue by nachawati** [gmessner/gitlab4j-api#57]
There doesn't seem to be a way to get the currently authenticated user via private token. The GitLab API provides this functionality (https://docs.gitlab.com/ce/api/users.html#user).

Could this be added in the near future?

**Comment by nachawati** [comment]
How about adding the following method to the UserApi class?

```
/**
 * Get currently authenticated user.
 *
 * GET /user
 *
 * @return the User instance for the currently authenticated user
 * @throws GitLabApiException if any exception occurs
 */
public User getCurrentUser() throws GitLabApiException {
    Response response = get(Response.Status.OK, null, "user");
    return (response.readEntity(User.class));
}
```

**Comment by gmessner** [comment]
@nachawati 
I will add this to the next release, which should happen in the next few days.

**Comment by gmessner** [comment]
@nachawati 
Release 4.4.4 has been completed with UserApi.getCurrentUser() added.
