### ISSUE TITLE
Getting null values for created_at, projects_limit, etc...

### ISSUE THREAD

**Issue by nachawati** [gmessner/gitlab4j-api#58]
There seems to be a problem deserializing JSON object keys from the GitLab API that contain underscores, such as created_at, projects_limit, etc... 

A simple fix might be to add @XmlAttribute to the relevant getter methods for classes in the org.gitlab4j.api.models.* package.

**Comment by gmessner** [comment]
There is extensive unit tests demonstrating that the serialization working correctly.  If you are trying to use the classes in org.gitlab4j.api.models package outside of the various API objects, you must use the ObjectMapper found in org.gitlab4j.api.utils.JacksonJson.  This takes care of all the name mapping and serialization/deserialization of various types like dates, enums, etc.

See the TestGitLabApiBeans unit test for an example.
