### ISSUE TITLE
Events API?

### ISSUE THREAD

**Issue by demaniak** [gmessner/gitlab4j-api#60]
Ref: https://gitlab.com/help/api/events.md

I note there is a `org.gitlab4j.api.models.Event` class mentioned in the [JavaDoc](http://www.messners.com/gitlab4j-api/javadocs/index.html?org/gitlab4j/api/package-summary.html), which seems to map to the Event API responses.

But I can't see how I could query the API with present API implementations?

Thanks.

**Comment by gmessner** [comment]
Currently there is only partial support for events, you can use the ProjectsApi and get all  events associated with the project:

```java
public List<Event> getProjectEvents(Integer projectId)
public List<Event> getProjectEvents(Integer projectId, int page, int perPage)
public Pager<Event> getProjectEvents(Integer projectId, int itemsPerPage) 
```

The Events API now has more robust support with 3 end points:

GET /events
GET /users/:id/events
GET /:project_id/events

I'll add an EventsApi class and fully implement these 3 in the next release, which is currently scheduled for 8/14/2017.

**Comment by demaniak** [comment]
Ah thanks, that would be grand!

Personally I am especially interested in the `/users:id/events` end point, since that should allow me to build an event log for a given user without having to trawl through all associated groups/projects.

**Comment by gmessner** [comment]
The Events API has been added and release 4.4.5 is now available.
