### ISSUE TITLE
Member.getEmail() cannot get email and return null

### ISSUE THREAD

**Issue by neillau24** [gmessner/gitlab4j-api#61]
Member.getEmail() cannot get email and return null

**Comment by gmessner** [comment]
For security reasons, the GitLab API removed email from member some time ago.  The only way to get a users email is to use the UserApi as an "admin" user and make one of the following calls:

All users: UserApi.getUsers() // The are several versions of this call
A single user: UserApi.getUser(Integer userId) // The are several versions of this call
Find users: UserApi.findUsers() // The are several versions of this call

<b>IMPORTANT:  Unless you are an admin user, email will not be returned.</b>

The Member class will eventually remove the email property, right now it remains to support people using it for very old GitLab servers.
