### ISSUE TITLE
Add method to UserApi for getting user by username

### ISSUE THREAD

**Issue by nachawati** [gmessner/gitlab4j-api#64]
The GitLab REST API currently supports getting a user by username via the following
GET /users?username=:username

Could this functionality be added to gitlab4j in the near future?

**Comment by gmessner** [comment]
I will have this added in the next release schedule for 8/21/2017.  The method signature will be:

```java
public User getUser(string username)
```

**Comment by gmessner** [comment]
UserApi.getUser(String username) has been added to 4.4.6.

Keep in mind that this will only work for admin users.
