### ISSUE TITLE
why can not the repositoryApi create default master branch ?

### ISSUE THREAD

**Issue by 383124397** [gmessner/gitlab4j-api#66]
for example:
1. gitLabApi.getProjectApi().createProject(p);
2. Project p = gitLabApi.getProjectApi().getProject("xxxxxx", name);
3. List<Branch> branchs = gitLabApi.getRepositoryApi().getBranches(p.getId());
finnally I find that the branchs is empty. but failed when I try to create dev branch:
4. gitLabApi.getRepositoryApi().createBranch(p.getId(), "dev", "master");

I wanna to do this steps:
create project with an empty repository -> upload a READ.ME file by API (or must by manual?) -> create branch from master -> ...

**Comment by gmessner** [comment]
@383124397 
Until you create a branch off of the "master" branch or add a file to the "master" branch, GitLab will not show any branches.

When you create the "dev" branch, a README.md file will automatically be created on "master" and will be in both the "master" and "dev" branches.
