### ISSUE TITLE
How do I pass statistics=true as a param to /projects?

### ISSUE THREAD

**Issue by aram535** [gmessner/gitlab4j-api#75]
Hi, 

I need to collect the statistics for the projects on our gitlab instance.   This is done by adding &statistics=true to the /projects request.

**Comment by aram535** [comment]
I found my answer in the code, there exists an overload getProjects( ... boolean statistics, ...).

**Comment by gmessner** [comment]
@aram535 
You'll find overloaded methods like this because GitLab continually adds things like this, really hard to keep up with them ;-)
