### ISSUE TITLE
Pager cannot access Project List with options

### ISSUE THREAD

**Issue by aram535** [gmessner/gitlab4j-api#76]
This works:

`        List<Project> projects = api.getProjectApi().getProjects(false, Visibility.PUBLIC,
                        Constants.ProjectOrderBy.NAME, Constants.SortOrder.DESC, null, true, true, true, false, true);
`

This gives you an error

`
        Pager<Project> projectPager = api.getProjectApi().getProjects(false, Visibility.PUBLIC,
                        Constants.ProjectOrderBy.NAME, Constants.SortOrder.DESC, null, true, true, true, false, true);
`

It also would be great if the getProjectsApi().getProjects( GitLabApiForm ) would exist so that we can make our own Form and pass it in, rather than be forced to set criteria that may limit the return.  For example.  I wanted "ALL" projects but the Visibility class forces me to do two calls one for INTERNAL and one for PRIVATE repositories. 

Realistically I just want to be able to get all projects with Statistics and owned (rather than forked) projects.  Happy to provide a Pull Request if that's easier.

**Comment by gmessner** [comment]
@aram535 

```java
Pager<Project> projectPager = api.getProjectApi().getProjects(
    false, Visibility.PUBLIC,
    Constants.ProjectOrderBy.NAME, Constants.SortOrder.DESC, 
    null, true, true, true, false, true);
```

Should have an additional parameter for how many items per page:

```java
Pager<Project> projectPager = api.getProjectApi().getProjects(
    false, Visibility.PUBLIC,
    Constants.ProjectOrderBy.NAME, Constants.SortOrder.DESC,
    null, true, true, true, false, true, 20);
```

**Comment by aram535** [comment]
Thank you for that.  One feedback on a previous comment - the Visibility param cannot be null.  It leads an NPE.  So if you want all projects no matter the visibility, you have to make multiple calls.

**Comment by gmessner** [comment]
@aram535 
I am not able to replicate the NPE with visibility being null.  Can you provide a stack trace?

Additionally, the GitLAB API does not allow multiple values for visibility when listing projects, so we need to get to the bottom of what is causing your problem with a null Visibility.

**Comment by gmessner** [comment]
@aram535 
Just wondering if you are still having issues?  I'd like to help resolve them if you do.

**Comment by aram535** [comment]
@gmessner sorry about that.  I must have missed the original notification from the post above.   I'm fairly sure I dump my junits from the above but I'll try to replicate it.  As far as visibility, I didn't want to apply any filter, with an admin token I like to get all projects regardless of their visibility settings.

So what I'm doing right now is using /api/v4/projects?statistics=true to get the projects than paginating through them 100 at a time until I have a full List<GitlabProject> object.  Now I can stream or whatever to get the stats/information I need.

**Comment by gmessner** [comment]
@aram535 
I am still not able to replicate your NPE when visibility is null.  I will add a unit test for this to verify and include in the next release.

**Comment by aram535** [comment]
I did chuck my junits, but I can't replicate it so I must have been doing something wrong.   Thanks for following up on this.
