### ISSUE TITLE
Some set methods of git entities seems redundant.

### ISSUE THREAD

**Issue by ozgurakpinar** [gmessner/gitlab4j-api#77]
I was trying find a way to set the **"merge_status**" of a merge request using gitlab4j api. `updateMergeRequest()` function does not have the parameter. Then I wanted to know what `MergeRequest::setMergeStatus()` does actually. 

It doesn't do anything except setting the field of the MergeRequest object. But the object is cannot be used to update merge request. Then what is it for? Maybe they should be removed from the api?

**Comment by gmessner** [comment]
The various set methods are used to by the API to populate the object from data returned by the calls to the GitLab API endpoints.   If the set methods are not present then the merge_status could not be fetched from the GitLab server.  

The GitLab API does not provide a way to modify the merge_status directly, you must call one of these methods to do so:

```java
public MergeRequest acceptMergeRequest(Integer projectId, Integer mergeRequestId, 
            String mergeCommitMessage, Boolean shouldRemoveSourceBranch, Boolean mergeWhenPipelineSucceeds)
public MergeRequest approveMergeRequest(Integer projectId, Integer mergeRequestId, String sha)
public MergeRequest cancelMergeRequest(Integer projectId, Integer mergeRequestId)
public MergeRequest unapproveMergeRequest(Integer projectId, Integer mergeRequestId)
```
