### ISSUE TITLE
OAuth2 tokens support

### ISSUE THREAD

**Issue by LilAlex** [gmessner/gitlab4j-api#79]
Hi,

It seems that currently only **login/password** and **private_token** is supported or is there any way to use **[access_token](https://docs.gitlab.com/ee/api/README.html#oauth2-tokens)** instead?

For example:
> https://gitlab.com/api/v4/projects?access_token=token

Thanks.

**Comment by gmessner** [comment]
@LilAlex 
I Have added support to create a GitLabApi instance set up to operate with the access token.  See all the constructors that take a TokenType parameter.

This functionality has not been thoroughly tested.  If you could possibly test it and respond back with your results I would greatly appreciate it.

**Comment by LilAlex** [comment]
@gmessner 

> I Have added support to create a GitLabApi instance set up to operate with the access token. See all the constructors that take a TokenType parameter.

Thank you.

> This functionality has not been thoroughly tested. If you could possibly test it and respond back with your results I would greatly appreciate it.

Okay, sure.
