### ISSUE TITLE
can i use root user to new a gitlabApiclient?

### ISSUE THREAD

**Issue by zhuzhiyang** [gmessner/gitlab4j-api#90]
i only have a root user,for example , i know the username is root,and i know the password for the root ,but i don't know the private token ,what can i do?

**Comment by gmessner** [comment]
You can use GitLabApi to login, see:

http://www.messners.com/gitlab4j-api/javadocs/org/gitlab4j/api/GitLabApi.html#login-java.lang.String-java.lang.String-java.lang.String-

```java
// Log in to the GitLab server using a username and password
GitLabApi gitLabApi = GitLabApi.login("http://your.gitlab.server.com", "your-username", "your-password");
```

**Comment by zhuzhiyang** [comment]
Ok!  Thank you very much
