### ISSUE TITLE
impersonation tokens

### ISSUE THREAD

**Issue by carllhw** [gmessner/gitlab4j-api#91]
Would it support impersonation tokens ?
I need create client by impersonation token.

Like by root user create user A's impersonation token.
Then access gitlab api by user A's new impersonation token

Gitlab API: https://docs.gitlab.com/ce/api/users.html#get-all-impersonation-tokens-of-a-user

**Comment by gmessner** [comment]
@carllhw 
Impersonation token support has been added to release 4.6.7
