### ISSUE TITLE
sudo

### ISSUE THREAD

**Issue by carllhw** [gmessner/gitlab4j-api#92]
Would it support sudo feature ?
I need create client by root user.
Then access gitlab api by root user and set header `SUDO: username`, like access gitlab api as other normal user

Gitlab API: https://docs.gitlab.com/ce/api/README.html#sudo

**Comment by gmessner** [comment]
@carllhw 
I have added sudo support in the next release of GitLab4-J, which will be released either 11/4 or 11/5. I will let you know when the release is complete.

**Comment by carllhw** [comment]
@gmessner Thanks

**Comment by gmessner** [comment]
@carllhw
Sudo support has been added in release 4.6.6, see the README.md file for more info.
