### ISSUE TITLE
Is possible to create notes and upload attachments?

### ISSUE THREAD

**Issue by monkiki** [gmessner/gitlab4j-api#97]
Hi there,

I've trying to create a note using this API but I can't find a method to do it. Is possible?

Regards.

**Comment by gmessner** [comment]
@monkiki 
If you could identify the particular calls at https://docs.gitlab.com/ce/api/notes.html, it would help me answer this question.

**Comment by monkiki** [comment]
I've been trying to use the REST API directly and have found some issues. I will contact GitLab people to get more information.

**Comment by gmessner** [comment]
@monkiki 
If you let me know what calls you would like to make I will look into supporting them, and will contribute fixes to any bugs I find in the GitLab API.

**Comment by monkiki** [comment]
I wanted to create a note setting a given creation date (created_at) and the creator (using sudo)
 (https://docs.gitlab.com/ce/api/notes.html#create-new-issue-note) . And as I have understood, only admin users can be set the creation date, so the sudo user should be an admin. The workaround was to grant the user admin permissions before the note creation, and revoke it after that.

**Comment by gmessner** [comment]
So it sounds like there is nothing to do for this issue.  Can you close it, or was there something you wanted investigated/added?

**Comment by monkiki** [comment]
Yes, I will close.

Thanks!
