### ISSUE TITLE
ForkAPI missing?

### ISSUE THREAD

**Issue by Spenhouet** [gmessner/gitlab4j-api#98]
I can't find anything about a ForkAPI. Is it possible to fork gitlab projects with this library?

https://docs.gitlab.com/ee/api/projects.html#fork-project

**Comment by gmessner** [comment]
The fork methods have not been implemented, I will implement them in the ProjectsApi in the next release which is scheduled for Monday, 12/4/2017

**Comment by gmessner** [comment]
@Spenhouet 
Fork project support was add and released in 4.7.0.

**Comment by Spenhouet** [comment]
@gmessner Really cool that the missing fork functionality was added this fast. I'm just testing out the fork implementation and I think it would be great if the `forkProject` method would return the new project (the fork) as `Project` instance.
